<?php
/* @var $this QSoft_ProductDesign_Block_Catalog_Product_View_Options */
?>
<?php
$_product = Mage::registry('current_product');
$colorMobileTab = $_product->getColorMobileTab();
$optionsTabs = $_product->getOptionTabs();

$relatedProducts = $_product->getRelatedProductIds();
$realatedCount = count($relatedProducts);

?>
<?php $_options = Mage::helper('core')->decorateArray($this->getOptions()) ?>
<?php if (count($_options)):?>
    <script type="text/javascript">
        function updateColorActive(id){
            jQuery('.qs-color-design.active').removeClass('active');
            jQuery('#' + id).addClass('active');
        }
        var optionsSlide = <?php echo $_product->getSlideJson(); ?>;
        optionsSlide['product-multi'] = '0';
        function makeOptionSlider(id, type) {
            var wd = jQuery(window).width();
            if(optionsSlide[id]=='0'){
                var slideQuantity = jQuery('#' + id + ' .swiper-slide').length;
                var slidesPerView = 6;

                var direction = 'vertical';
                if(wd<=1024){
                    direction = 'horizontal';
                    slidesPerView = 6;
                }
                if(wd<=767){
                    slidesPerView = 4;
                    slideQuantity = slideQuantity +2;
                }

                if(type=='size'){
                    if(wd<=1024){
                        slidesPerView = 6;
                    }
                    if(wd<=767){
                        slidesPerView = 4;
                    }
                }
                if(type=='multi'){
                    slideQuantity = slideQuantity + 3;
                    slidesPerView = 3;
                    if(wd<=1024){
                        slidesPerView = 4;
                        slideQuantity = slideQuantity +2;
                    }
                    if(wd<=767){
                        slidesPerView = 3;
                    }
                }

                if(slideQuantity<=6){
                    jQuery('#' + id + '-prev').hide();
                    jQuery('#' + id + '-next').hide();
                }

                if( slideQuantity>=1){
                    optionsSlide[id] = '1';
                    swiperO = new Swiper('#' + id,{
                        slidesPerView: slidesPerView,
                        mousewheelControl: true,
                        prevButton: '#' + id + '-prev',
                        nextButton: '#' + id + '-next',
                        direction: direction,
                        pagination:'#' + id + '-pagination',
                        paginationClickable: true,
                        paginationHide: true
                    });
                    setTimeout(function () {
                        swiperO.onResize();
                    }, 500);
                }

            }
        }
        function showPadDetail(id, el) {

            if(!jQuery(el).hasClass('pad-active')){
                jQuery('.qs-choose-pad').hide();
                jQuery('#qs-pad-' + id).show();
                jQuery('ul.list-group-pane').removeClass('has-active');
                jQuery('.pad-active').removeClass('pad-active');
                jQuery(el).addClass('pad-active');
                jQuery(el).parents('ul.list-group-pane').addClass('has-active');
                makeOptionSlider(id, 'pad');
            }
        }
        function activeProductValue(el) {
            if(jQuery(el).parent().hasClass('product-active')){
                jQuery(el).parent().removeClass('product-active');
            }else{
                jQuery(el).parent().addClass('product-active');
            }
        }

        function activePadValue(el) {
            jQuery('.pad-item-active').removeClass('pad-item-active');
            jQuery(el).parent().addClass('pad-item-active');
        }

        /*function showContentMobileTabColor() {
            jQuery('#option-tab-mobile-color').addClass('active');
        }*/

        function goToMobileColorItem(id, el) {
            jQuery('#' + id).trigger('click');
            jQuery('.qs-nav-tabs .mobile-color-tab').addClass('active');
            jQuery('#option-tab-mobile-color').addClass('active');
            jQuery('.list-mobile-color-item').find('.active').removeClass('active');
            jQuery(el).addClass('active');
        }
    </script>
    <script type="text/javascript">
    //<![CDATA[
    var optionFileUpload = {
        productForm : $('product_addtocart_form'),
        formAction : '',
        formElements : {},
        upload : function(element){
            this.formElements = this.productForm.select('input', 'select', 'textarea', 'button');
            this.removeRequire(element.readAttribute('id').sub('option_', ''));

            template = '<iframe id="upload_target" name="upload_target" style="width:0; height:0; border:0;"><\/iframe>';

            Element.insert($('option_'+element.readAttribute('id').sub('option_', '')+'_uploaded_file'), {after: template});

            this.formAction = this.productForm.action;

            var baseUrl = '<?php echo $this->getUrl('*/product/upload') ?>';
            var urlExt = 'option_id/'+element.readAttribute('id').sub('option_', '');

            this.productForm.action = parseSidUrl(baseUrl, urlExt);
            this.productForm.target = 'upload_target';
            this.productForm.submit();
            this.productForm.target = '';
            this.productForm.action = this.formAction;
        },
        removeRequire : function(skipElementId){
            for(var i=0; i<this.formElements.length; i++){
                if (this.formElements[i].readAttribute('id') != 'option_'+skipElementId+'_file' && this.formElements[i].type != 'button') {
                    this.formElements[i].disabled='disabled';
                }
            }
        },
        addRequire : function(skipElementId){
            for(var i=0; i<this.formElements.length; i++){
                if (this.formElements[i].readAttribute('name') != 'options_'+skipElementId+'_file' && this.formElements[i].type != 'button') {
                    this.formElements[i].disabled='';
                }
            }
        },
        uploadCallback : function(data){
            this.addRequire(data.optionId);
            $('upload_target').remove();

            if (data.error) {

            } else {
                $('option_'+data.optionId+'_uploaded_file').value = data.fileName;
                $('option_'+data.optionId+'_file').value = '';
                $('option_'+data.optionId+'_file').hide();
                $('option_'+data.optionId+'').hide();
                template = '<div id="option_'+data.optionId+'_file_box"><a href="#"><img src="var/options/'+data.fileName+'" alt=""><\/a><a href="#" onclick="optionFileUpload.removeFile('+data.optionId+')" title="Remove file" \/>Remove file<\/a>';

                Element.insert($('option_'+data.optionId+'_uploaded_file'), {after: template});
            }
        },
        removeFile : function(optionId)
        {
            $('option_'+optionId+'_uploaded_file').value= '';
            $('option_'+optionId+'_file').show();
            $('option_'+optionId+'').show();

            $('option_'+optionId+'_file_box').remove();
        }
    }
    var optionTextCounter = {
        count : function(field,cntfield,maxlimit){
            if (field.value.length > maxlimit){
                field.value = field.value.substring(0, maxlimit);
            } else {
                cntfield.innerHTML = maxlimit - field.value.length;
            }
        }
    }

    Product.Options = Class.create();
    Product.Options.prototype = {
        initialize : function(config) {
            this.config = config;
            this.reloadPrice();
            document.observe("dom:loaded", this.reloadPrice.bind(this));
        },
        reloadPrice : function() {
            var config = this.config;
            var skipIds = [];
            $$('body .product-custom-option').each(function(element){
                var optionId = 0;
                element.name.sub(/[0-9]+/, function(match){
                    optionId = parseInt(match[0], 10);
                });
                if (config[optionId]) {
                    var configOptions = config[optionId];
                    var curConfig = {price: 0};
                    if (element.type == 'checkbox' || element.type == 'radio') {
                        if (element.checked) {
                            if (typeof configOptions[element.getValue()] != 'undefined') {
                                curConfig = configOptions[element.getValue()];
                            }
                        }
                    } else if(element.hasClassName('datetime-picker') && !skipIds.include(optionId)) {
                        dateSelected = true;
                        $$('.product-custom-option[id^="options_' + optionId + '"]').each(function(dt){
                            if (dt.getValue() == '') {
                                dateSelected = false;
                            }
                        });
                        if (dateSelected) {
                            curConfig = configOptions;
                            skipIds[optionId] = optionId;
                        }
                    } else if(element.type == 'select-one' || element.type == 'select-multiple') {
                        if ('options' in element) {
                            $A(element.options).each(function(selectOption){
                                if ('selected' in selectOption && selectOption.selected) {
                                    if (typeof(configOptions[selectOption.value]) != 'undefined') {
                                        curConfig = configOptions[selectOption.value];
                                    }
                                }
                            });
                        }
                    } else {
                        if (element.getValue().strip() != '') {
                            curConfig = configOptions;
                        }
                    }
                    if(element.type == 'select-multiple' && ('options' in element)) {
                        $A(element.options).each(function(selectOption) {
                            if (('selected' in selectOption) && typeof(configOptions[selectOption.value]) != 'undefined') {
                                if (selectOption.selected) {
                                    curConfig = configOptions[selectOption.value];
                                } else {
                                    curConfig = {price: 0};
                                }
                                optionsPrice.addCustomPrices(optionId + '-' + selectOption.value, curConfig);
                                optionsPrice.reload();
                            }
                        });
                    } else {
                        optionsPrice.addCustomPrices(element.id || optionId, curConfig);
                        optionsPrice.reload();
                    }
                }
            });
        }
    }
    function validateOptionsCallback(elmId, result) {
        var container = $(elmId).up('ul.options-list');
        if (result == 'failed') {
            container.removeClassName('validation-passed');
            container.addClassName('validation-failed');
        } else {
            container.removeClassName('validation-failed');
            container.addClassName('validation-passed');
        }
    }
    var opConfig = new Product.Options(<?php echo $this->getJsonConfig() ?>);
    //]]>
    </script>
    <?php if(count($optionsTabs)): ?>

<div class="qs-control-top">
    <!-- Tab panel -->
    <div class="qs-control-tab">
        <ul class="qs-nav-tabs">
            <?php if(count($colorMobileTab)):?>
            <li class="mobile-color-tab" role="presentation" >
                <a class="qs-tab-group" href="#option-tab-mobile-color" onclick="showContentMobileTabColor();" aria-controls="option-tab-mobile-color">
                    <span class="co-ic co-ic-mobile-color"></span>
                    <span class="text">color</span>
                </a>
            </li>
            <?php endif;?>
            <?php $i=0; foreach($optionsTabs as $id=>$optionsTab): ?>
                    <li class="item item-<?php echo $optionsTab['class']?> <?php if($i==0):?>active<?php endif;?>" role="presentation" type="li-<?php echo $optionsTab['class']?>">
                        <a id="child-<?php echo $id?>" <?php if($optionsTab['type']!='pad'):?> onclick="makeOptionSlider('<?php echo $id ?>','<?php echo $optionsTab['type'] ?>');" <?php endif;?> class="qs-tab-group" href="#option-tab-<?php echo $id ?>" aria-controls="option-tab-<?php echo $id ?>">
                            <span class="co-ic co-ic-<?php echo $optionsTab['class']?>"></span>
                            <span class="text"><?php echo $optionsTab['label']?></span>
                        </a>
                        <input type="hidden" value="0" class="qs-validate-<?php echo $optionsTab['type']?>" />
                    </li>
                    <?php $i++; ?>
            <?php endforeach; ?>
            

        <?php if($realatedCount):?>
            <li class="item item-group-is-multi " role="presentation" type="li-group-is-multi">
                <a id="child-product-multi" onclick="makeOptionSlider('product-multi','multi');" class="qs-tab-group" href="#option-tab-product-multi" aria-controls="option-tab-product-multi">
                    <span class="co-ic icon-accessories"></span>
                    <span class="text">Accessories</span>
                </a>
                <input value="0" class="qs-validate-multi" type="hidden">
            </li>
        <?php endif;?>
            <li class="item item-see-detail" role="presentation">
                <a class="qs-tab-group" href="#see-detail" aria-controls="see-detail">
                    <span class="co-ic co-ic-see-detail"></span>
                    <span class="text">See detail</span>
                </a>
            </li>
        </ul>

        <!-- Tab panes -->
        <div class="qs-tab-content">
        <?php if(count($colorMobileTab)):?>
            <?php echo $this->getOptionTabMobileContent($colorMobileTab) ?>
        <?php endif;?>

            <?php
            $firstSliderId = '';
            $firstSliderType = '';
            $firstSliderClass = '';
            ?>
            <?php $j=0; foreach($optionsTabs as $id=>$optionsTab): ?>
                <?php $class=''; if($j==0):?>
                    <?php
                    $class = 'active';
                    $firstSliderId = $id;
                    $firstSliderType = $optionsTab['type'];
                    $firstSliderClass = 'item-' . $optionsTab['class'];
                    ?>
                <?php endif;?>
                    <?php echo $this->getOptionTabContent($id, $optionsTab, $class) ?>
            <?php $j++; endforeach; ?>

            <script type="text/javascript">
                    jQuery('.<?php echo $firstSliderClass?>').trigger('click');
                    makeOptionSlider('<?php echo $firstSliderId ?>', '<?php echo $firstSliderType?>');
            </script>
            <?php
            $colorGroup = explode(',', Mage::getStoreConfig('productdesign/group_type/color'));
            $sizeGroup = explode(',', Mage::getStoreConfig('productdesign/group_type/size'));
            $givingGroup = explode(',', Mage::getStoreConfig('productdesign/group_type/giving_name'));
            ?>
        <?php if($realatedCount):?>
            <div class="qs-tab-pane product-pane" id="option-tab-product-multi">
                <div id="product-multi" class="wp-container-slider wp-product-slider swiper-container-vertical">
                    <div id="product-multi-prev" class="swiper-prev">Pre</div>
                    <div class="swiper-wrapper">
                <?php foreach($relatedProducts as $_item): ?>
                    <?php $_item = Mage::getModel('catalog/product')->load($_item);?>
                    <?php if($_item->getStatus()==Mage_Catalog_Model_Product_Status::STATUS_ENABLED):?>
                        <div class="swiper-slide qs-row-choose-multi">
                            <input class="op-product-product body-size checkbox  product-custom-option"
                                   title="<?php echo $_item->getName()?>"
                                   onclick="activeProductValue(this);opConfig.reloadPrice(); updateTabInfo('product','product','price679','<?php echo $_item->getName()?>');"
                                   name="related_products[]"
                                   id="related-<?php echo $_item->getId()?>" value="<?php echo $_item->getId()?>"  type="checkbox">
                            <label for="related-<?php echo $_item->getId()?>" title="<?php echo $_item->getName()?>">
                                <img alt="<?php echo $_item->getName()?>" src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(150) ?>">
                                <div class="show-hover">
                                    <span class="title-text"><?php echo $_item->getName()?> </span>
                                </div>
                            </label>
                        </div>
                    <?php endif;?>
                <?php endforeach; ?>
                   </div>
                    <div id="product-multi-next" class="swiper-next">Next</div>
                    <div id="product-multi-pagination" class="swiper-pagination-option"></div>
                </div>
            </div>
        <?php endif;?>
            <div class="qs-tab-pane see-detail-pane" id="see-detail">
                <div class="pane-content">
                    <div class="title"><?php echo $this->__('See Detail') ?></div>
                    <div class="pane-info">
                        <div class="pane-option">
                            <?php foreach($_options as $_option): ?>
                                    <div class="item-option item-color">
                                        <label id="option-label-<?php echo $_option->getId()?>" class="lb-option"><?php echo $_option->getTitle()?></label>
                                        <div class="group-value">
                                            <div class="qs-row-option-detail">
                                                <span id="option-<?php echo $_option->getId()?>-price" class="qs-price-option"></span>
                                                <span class="qs-name-option-detail"><span id="option-<?php echo $_option->getId()?>-label"></span></span>
                                            </div>
                                        </div>
                                    </div>
                            <?php endforeach;?>
        <?php if($realatedCount):?>
            <div class="item-option item-color">
                <label class="lb-option">Product</label>
                <div class="group-value">
                    <div class="qs-row-option-detail">
                        <span id="option-product-price" class="qs-price-option"></span>
                        <span class="qs-name-option-detail"><span id="option-product-label"></span></span>
                    </div>
                </div>
            </div>
        <?php endif;?>
                        </div>
                        <div class="pane-action">
                            <div class="bx-qty">
                                <label for="qty">Quantity</label>
                                <div class="select-qty">
                                    <input id="input-qty" name="qty" min="1" type="text" class="input-qty">
                                    <select  class="select-qty" onchange="updateInputQty(this);">
                                        <?php for($i=1; $i<=10; $i++):?>
                                        <option value="<?php echo $i?>"><?php echo $i ?></option>
                                        <?php endfor;?>
                                    </select>
                                </div>
                            </div>
                            <div class="bx-price">
                                <?php echo $this->getLayout()->getBlock('product.clone_prices')->toHtml(); ?>
                            </div>
                            <div class="bx-action">
                                <button type="button" title="Add To Cart" onclick="productAddToCartForm.submit(this)"><?php echo $this->__('Add To Cart') ?></button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
    <?php else:?>
        <dl>
            <?php foreach($_options as $_option): ?>
                <?php echo $this->getOptionHtml($_option) ?>
            <?php endforeach; ?>
        </dl>
    <?php endif;?>
    
<?php endif; ?>

<script type="text/javascript">
    function updateInputQty(elm) {
        jQuery('#input-qty').val(elm.value);
    }
</script>