<?php $_productChart = $this->getProduct()->getProductChart(); ?>
<?php if ($_productChart): ?>
    <div class="std">
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($_productChart)->toHtml() ?>
    </div>
    <script type="text/javascript">
        jQuery(document).ready(function () {
            jQuery('.qs-row-measure input[type=radio]').each(function () {
                jQuery(this).click(function () {
                    if(this.value=='cm'){
                        jQuery('#sizechart_cm').show();
                        jQuery('#sizechart_inch').hide();
                    }else{
                        jQuery('#sizechart_cm').hide();
                        jQuery('#sizechart_inch').show();
                    }
                })
            })
        })
    </script>
<?php endif; ?>