<script type="text/javascript">countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?></script>
<?php
echo $this->getDesignStyles();
$package = Mage::getDesign()->getPackageName();
$theme = Mage::getDesign()->getTheme('frontend');
$is_persistent = Mage::helper('onestepcheckout')->isPersistentMember();
?>

<!--<div class="qs-banner-page" data-parallax="scroll" data-image-src="--><?php //echo $this->getSkinUrl('images/schedule_page.jpg') ?><!--">&nbsp;</div>-->
<div class="opc-wrapper-opc qs-page-container design_package_<?php echo $package;?> design_theme_<?php echo $theme;?>">
	<div class="container">
		<h1 class="qs-page-title"><?php echo $this->__('Checkout')?></h1>
		<div class="qs-desc-opc-page"><?php echo $this->__('Welcome to the checkout. Fill in the fields below to complete your purchase!') ?></div>
		<div class="opc-menu">
			<?php if(!$is_persistent):?>
				<?php echo $this->getMessagesBlock()->getGroupedHtml(); ?>
				<?php echo $this->getChildHtml('paypal.button'); ?>

				<?php if (!Mage::getSingleton('customer/session')->isLoggedIn()):?>
					<?php echo $this->getChildHtml('login');?>
				<?php endif;?>
			<?php else:?>
				<?php echo $this->getChildHtml('login');?>
			<?php endif;?>
		</div>

		<div <?php if($is_persistent):?>style="display:none !important;"<?php endif;?>>
			<div class="qs-opc-container">
				<div class="row">
					<div class="col-sm-6">
						<div class="qs-col-opc-left">
							<form id="opc-address-form-billing" method="post">
								<?php echo $this->getChildHtml('billing')?>
							</form>

							<form id="opc-address-form-shipping" class="hidden" method="post">
								<?php echo $this->getChildHtml('shipping')?>
							</form>

							<?php if (!$this->getOnepage()->getQuote()->isVirtual()):?>
								<div class="shipping-block">
									<h3 class="opc-title-block"><i class="qs-icon-opc qs-icon-shipping"></i><?php echo $this->__('Shipping Method')?></h3>
									<div id="shipping-block-methods">
										<?php echo $this->getChildHtml('shipping_method');//$this->_getShippingMethodsHtml();?>
									</div>
								</div>
							<?php endif;?>

							<?php if(Mage::helper('onestepcheckout')->isShowDiscount()):?>
								<div class="discount-block">
									<h3><i class="qs-icon-opc qs-icon-giftcode"></i><?php echo $this->__('Discount Codes')?></h3>
									<div  class="collapse-block">
										<?php echo $this->getChildhtml('coupon');?>
									</div>
								</div>
							<?php endif;?>

							<?php if(Mage::helper('onestepcheckout')->isShowComment()):?>
								<?php echo $this->getChildhtml('customer.comment');?>
							<?php endif;?>

							<div class="payment-block <?php if ($this->getOnepage()->getQuote()->isVirtual()):?>clear-margin<?php endif;?>">
								<h3 class="opc-title-block"><i class="qs-icon-opc qs-icon-payment"></i><?php echo $this->__('Payment Method')?></h3>
								<?php echo $this->getChildHtml('payment')//$this->_getPaymentMethodsHtml();?>
							</div>
						</div>
					</div>
					<div class="col-sm-6">
						<div class="qs-col-opc-right">
							<div id="opc-review-block">
								<?php echo $this->_getReviewHtml()?>
							</div>

							<div class="opc-review-actions" id="checkout-review-submit">
								<?php echo $this->getChildHtml('agreements')?>
								<?php echo $this->getChildHtml('onestepcheckout.newsletters');?>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="qs-row-button">
				<div class=row>
					<div class="col-sm-6"><div class="qs-continue-shop"><a href="<?php echo Mage::getBaseUrl(); ?>"><?php echo $this->__('Continue Shopping') ?></a></div></div>
					<div class="col-sm-6"><button type="button" title="<?php echo $this->__('Place Order Now') ?>" class="button btn-checkout opc-btn-checkout"><?php echo $this->__('Place Order Now') ?></button></div>
				</div>
			</div>
		</div>
	</div>
</div>
<script>
	//<![CDATA[
	var vopc = '<?php echo Mage::getConfig()->getModuleConfig("Qsoft_Onestepcheckout")->version;?>';
	Qsoft.Onestepcheckout.Checkout.config = '<?php echo $this->getJsonConfig()?>';
	<?php if ($this->getOnepage()->getQuote()->isVirtual()):?>
	Qsoft.Onestepcheckout.Checkout.isVirtual = true;
	<?php endif;?>

	jQuery('#billing\\:telephone, #shipping\\:telephone').keypress(function (event) {
		if ((event.which != 46 || jQuery(this).val().indexOf('.') != -1) && (event.which < 48 || event.which > 57) && event.which != 8) {
			event.preventDefault();
		}
	});
	//jQuery('#billing\\:telephone, #shipping\\:telephone').mask("999-999-9999");
	//]]>
</script>

<div id="agree_error" style="display:none !important;"><?php echo $this->__('Please agree to all the terms and conditions before placing the order.');?></div>
<div id="pssm_msg" style="display:none !important;"><?php echo $this->__('Please specify shipping method.');?></div>
<div class="opc-ajax-loader">
	<div id="floatingCirclesG">
		<div class="f_circleG" id="frotateG_01"></div>
		<div class="f_circleG" id="frotateG_02"></div>
		<div class="f_circleG" id="frotateG_03"></div>
		<div class="f_circleG" id="frotateG_04"></div>
		<div class="f_circleG" id="frotateG_05"></div>
		<div class="f_circleG" id="frotateG_06"></div>
		<div class="f_circleG" id="frotateG_07"></div>
		<div class="f_circleG" id="frotateG_08"></div>
	</div>
</div>
<div class="opc-message-wrapper design_package_<?php echo $package;?> design_theme_<?php echo $theme;?>">

	<div class="opc-messages">
		<a class="close-message-wrapper"><i class="fa fa-close"></i></a>
		<div class="opc-message-container"></div>
		<div class="opc-messages-action"><button class="button"><span><span><?php echo $this->__('Close')?></span></span></button></div>
	</div>
</div>