<?php
/**
 * @var QSoft_Customer_Block_Customer_Account_Navigation $this
 *
 */
$menus = array(
        'account','customer_measure','account_edit','orders','wishlist','newsletter'
);
?>
<div class="block block-account block-list-menu">
    <!-- <div class="block-title">
        <strong><span><?php echo $this->__('My Account'); ?></span></strong>
    </div> -->
    
    <!-- <div class="text-list hide-on-mobile hide-on-desktop js-show-list"><span>Account Dashboard</span><i class="fa fa-caret-down"></i></div> -->
    <div class="block-content">
        <i class="fa fa-caret-down js-show-list drop-down-icon"></i>
        <ul class="list-icon-style">
            <?php $_links = $this->getLinks(); ?>
            <?php $_index = 1; ?>
            <?php $_count = count($_links); ?>
            <?php foreach ($menus as $menu):?>
                <?php foreach ($_links as $_link): ?>
                    <?php if($menu==$_link->getName()):?>
                        <?php $_last = ($_index++ >= $_count); ?>
                        <?php if ($this->isActive($_link)): ?>
                            <li class="nav-<?php echo $menu;?> current<?php echo ($_last ? ' last' : '') ?>">
                                <a href="<?php echo $_link->getUrl() ?>"><span><?php echo $_link->getLabel() ?></span></a>
                            </li>
                        <?php else: ?>
                            <li class="nav-<?php echo $menu;?> <?php echo ($_last ? ' last' : '') ?>">
                                <a href="<?php echo $_link->getUrl() ?>"><span><?php echo $_link->getLabel() ?></span></a>
                            </li>
                        <?php endif; ?>
                    <?php endif; ?>
                <?php endforeach; ?>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
