<?php
/**
 * @category    MT
 * @package     MT_Extensions
 * @copyright   Copyright (C) 2008-2013 MagentoThemes.net. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      MagentoThemes.net
 * @email       support@magentothemes.net
 */
?>
<?php
/**
 * MT_Extensions_Block_Adminhtml_Widget_Form_Browser
 */
?>
<tr>
    <td class="label">
        <label for="<?php echo $this->getElement()->getHtmlId()?>"><?php echo  $this->getElement()->getLabel()?></label>
    </td>
    <td class="value">
        <img src="<?php echo $this->getElement()->getValue()?>" width="100" id="preview_<?php echo $this->getElement()->getHtmlId()?>"/>
        <input
            id="<?php echo $this->getElement()->getHtmlId()?>"
            name="<?php echo $this->getElement()->getName()?>"
            value="<?php echo $this->getElement()->getValue()?>"
            title="<?php echo $this->getElement()->getTitle()?>"
            onclick="<?php echo $this->getElement()->getData('onclick')?>"
            onchange="updateCurrentImg(this);"
            <?php if ($this->getElement()->getData('readonly') == true):?>readonly<?php endif ?>
            type="hidden"
            class="input-text"
            style="width:220px;vertical-align:top;"/>
        <?php echo  $this->getChildHtml('browserBtn') ?>
        <?php echo  $this->getChildHtml('clearBtn') ?>
        <?php if ($note = $this->getElement()->getData('note')):?>
        <p class="note" id="note_delay">
            <span><?php echo $note?></span>
        </p>
        <?php endif?>
    </td>
</tr>
<script type="text/javascript">
    window.on_<?php echo $this->getElement()->getHtmlId()?>_clear_click = function(){
        var target = $('<?php echo $this->getElement()->getHtmlId()?>');
        if (target){
            target.value = '';
            if (fireEvent) fireEvent(target, 'change');
        }
    };
    function updateCurrentImg(element){
        var img = window.document.getElementById('preview_' + element.id);
        img.src = element.value;
    }
</script>