<?php 
$store = Mage::app()->getStore();
$categories = $this->getParentCategories();
$columnNumber = $this->getColumnNumber();
$col_index = round(12/$columnNumber,0);
$column = $columnNumber-1;
$show_all_link = $this->getItem()->getSubtitleFontSize();
$enable_image = $this->getItem()->getCategoryImage();
?>
<?php if (count($this->getCategories())): ?>  
<div class="row ms-category-dynamic">
    <div class="col-category col-xs-12">
        <div class="row">
            
            <div class="col-level col-xs-<?php echo $col_index;?>">  
            <?php $i=1;foreach($categories as $category): ?>
                <?php $childrens = $this->getChildrenCategoriesByLevel($category,3);?>
                <div class="col-xs-12 form-group<?php if($i==1):?> active<?php endif;?><?php if(count($childrens) >0) :?> parent<?php endif;?><?php if($i == count($categories)):?> last<?php endif;?>" href="dynamic-<?php echo $category->getId();?>" alt="submenu-<?php echo $this->getItem()->getId(); ?>">
                    <a title="<?php echo $category->getName() ?>" href="<?php echo $category->getUrl() ?>"><small class="glyphicon glyphicon-th-large">&nbsp;</small><?php echo $category->getName() ?><?php if(count($childrens) >0) :?><small class="glyphicon glyphicon-chevron-right small">&nbsp;</small><?php endif;?></a>
                </div>
            <?php $i++; endforeach;?>
            </div>
          
            <div class="col-xs-<?php echo 12-$col_index;?> dynamic-content">
            <?php $i=1;foreach($categories as $category): ?>
            <?php $childrens = $this->getChildrenCategoriesByLevel($category,3);?>
                <?php $numbers = count($childrens);
                    $col_index2 = floor(12/$column);
                    switch ($column) {
                        case 5:$col_index2 = 24;
                                break;
                        case 7:$col_index2 = 14;
                                break;  
                        case 8:$col_index2 = 125;
                                break;
                        case 9:$col_index2 = 111;
                            break; 
                        case 10:$col_index2 = 100;
                            break; 
                        case 11:$col_index2 = 909;
                                break; 
                        default:
                            break;
                    }
                        $add_cat = 0;
						
                       if($numbers%$column==0){
                            $num_cat = $numbers/$column;
                        }else{
                            $num_cat = floor($numbers/$column) +1;
                            $add_cat = $numbers%$column;
                        };
                ?>
                <?php if(count($childrens) >0) :?>
                <div class="form-group col-dynamic<?php if($i==1): ?> active<?php endif;?>" id="dynamic-<?php echo $category->getId();?>"> 
                <?php $j=1;$k=0; foreach($childrens as $children):?>
                <?php if($j==1): ?>
                <div class="col-xs-<?php echo $col_index2 ?>">
                <?php $k++; endif;?>
                <div class="form-group text-center">
                <?php $_imgHtml   = '';
                    if ($_imgUrl = $children->getImageUrl()) {
                        $_imgHtml = '<img src="'.$_imgUrl.'" alt="'.$this->escapeHtml($children->getName()).'" title="'.$this->escapeHtml($children->getName()).'" />';
                        $_imgHtml = $this->helper('catalog/output')->categoryAttribute($children, $_imgHtml, 'image');
                    }else{
                        $_imgHtml = '<img src="'.Mage::getBaseUrl("media").'megamenu/sample_data/magento.png" alt="'.$this->escapeHtml($children->getName()).'" title="'.$this->escapeHtml($children->getName()).'"/>';
                    }
                ?>
                    <a href="<?php echo $children->getUrl() ?>" title="<?php echo $children->getName() ?>">
                <?php if($enable_image): ?>
                    <span class="form-group col-category-image"><?php echo $_imgHtml;?></span>
                <?php endif;?>
                    <span class="form-group col-category-name"><?php echo $children->getName() ?></span> 
                    </a>
                </div>
                <?php if($j==$num_cat): ?>
                </div>
                <?php if($add_cat != 0 && $k >= $add_cat) $num_cat= floor($numbers/$column) ; ?> 
                <?php endif;?>
                <?php  if($j<$num_cat) $j++;else $j=1; endforeach;?>
                <?php if($show_all_link):?>
                <div class="col-xs-12">
                    <a class="dynamic-viewall" href="<?php echo $category->getUrl(); ?>"><?php echo $this->__('View All');?><small class="glyphicon glyphicon-share-alt">&nbsp;</small></a>
                </div>
                <?php endif;?>
                </div>  
              <?php endif; ?>
            <?php $i++; endforeach;?>
            </div>
      
        </div>
    </div>
</div>
<style>
    #submenu-<?php echo $this->getItem()->getId(); ?>{padding-top:0;padding-bottom:0;}
    #submenu-<?php echo $this->getItem()->getId(); ?> .ms-header{margin-bottom:0;}
    #submenu-<?php echo $this->getItem()->getId(); ?> .ms-footer{margin-top:0;}
</style>
<?php endif; ?>