<?php 
$categories = $this->getParentCategories();
?>
 <?php if (count($this->getCategories())): ?>  
<div class="row ms-category-level">
    <div class="col-category col-xs-12">
        <div class="row">
            <?php $i=1;foreach($categories as $category): ?>
            <?php $childrens = $this->getChildrenCategoriesByLevel($category,2);?>
            <div class="col-xs-12 col-level <?php if(count($childrens) >0) echo 'parent' ?>">  
                <a class="form-group " href="<?php echo $category->getUrl() ?>"><small class="glyphicon glyphicon-th-large">&nbsp;</small><?php echo $category->getName() ?><?php if(count($childrens) >0) :?><small class="glyphicon glyphicon-chevron-right small">&nbsp;</small><?php endif;?></a>
                <?php if(count($childrens) >0) :?>
                <div class="col-xs-12 col-sub">
                    <div class="row">
                <?php foreach($childrens as $children):?>
                 <?php $childs =  $this->getChildrenCategoriesByLevel($children,3) ?>
                    <div class="col-xs-12<?php if(count($childs) >0):?> parent<?php endif;?>">
                    <a class="form-group" href="<?php echo $children->getUrl() ?>"><small class="glyphicon glyphicon-th-large">&nbsp;</small><?php echo $children->getName() ?><?php if(count($childs) >0):?><small class="glyphicon glyphicon-chevron-right small">&nbsp;</small><?php endif;?></a> 
                    <?php if($children->hasChildren() && count($childs)>0): ?>
                    <div class="col-xs-12 col-sub">
                        <?php foreach($childs as $child): ?>
                            <a class="form-group" href="<?php echo $child->getUrl() ?>"><small class="glyphicon glyphicon-th-large">&nbsp;</small><?php echo $child->getName() ?></a>
                        <?php  endforeach;?>
                    </div>
                    <?php  endif;?>
                    </div>
                <?php endforeach;?>
                    </div>
                </div>
                <?php endif; ?>
            </div>
            <?php endforeach;?>
        </div>
    </div>
</div>
 <?php endif; ?>