<?php

/**
 * Nwdthemes Revolution Slider Extension
 *
 * @package     Revslider
 * @author		Nwdthemes <mail@nwdthemes.com>
 * @link		http://nwdthemes.com/
 * @copyright   Copyright (c) 2014. Nwdthemes
 * @license     http://themeforest.net/licenses/terms/regular
 */

	$api =  "revapi".$this->sliderID;
?>

	<div id="api_wrapper" class="api_wrapper postbox unite-postbox ">
			<h3 class="box_closed tp-accordion tpa-closed"><div class="postbox-arrow"></div><i style="float:left;margin-top:4px;font-size:14px;" class="eg-icon-tools"></i><span><?php echo $this->__("API Functions") ?></span></h3>
			<div class="toggled-content tp-closedatstart p20">
					<div class="api-caption"><?php echo $this->__("API Methods")?>:</div>
					<div class="divide20"></div>
					<div class="api-desc"><?php echo $this->__("Please copy / paste those functions into your functions js file")?>. </div>

					<table class="api-table">
						<tr>
							<td class="api-cell1"><?php echo $this->__("Pause Slider")?>:</td>
							<td class="api-cell2"><input type="text" readonly  class="api-input" value="<?php echo $api?>.revpause();"></td>
						</tr>
						<tr>
							<td class="api-cell1"><?php echo $this->__("Resume Slider")?>:</td>
							<td class="api-cell2"><input type="text" readonly class="api-input" value="<?php echo $api?>.revresume();"></td>
						</tr>
						<tr>
							<td class="api-cell1"><?php echo $this->__("Previous Slide")?>:</td>
							<td class="api-cell2"><input type="text" readonly class="api-input" value="<?php echo $api?>.revprev();"></td>
						</tr>
						<tr>
							<td class="api-cell1"><?php echo $this->__("Next Slide")?>:</td>
							<td class="api-cell2"><input type="text" readonly class="api-input" value="<?php echo $api?>.revnext();"></td>
						</tr>
						<tr>
							<td class="api-cell1"><?php echo $this->__("Go To Slide")?>:</td>
							<td class="api-cell2"><input type="text" readonly class="api-input" value="<?php echo $api?>.revshowslide(2);"></td>
						</tr>
						<tr>
							<td class="api-cell1"><?php echo $this->__("Get Num Slides")?>:</td>
							<td class="api-cell2"><input type="text" readonly class="api-input" value="<?php echo $api?>.revmaxslide();"></td>
						</tr>
						<tr>
							<td class="api-cell1"><?php echo $this->__("Get Current Slide Number")?>:</td>
							<td class="api-cell2"><input type="text" readonly class="api-input" value="<?php echo $api?>.revcurrentslide();"></td>
						</tr>
						<tr>
							<td class="api-cell1"><?php echo $this->__("Get Last Playing Slide Number")?>:</td>
							<td class="api-cell2"><input type="text" readonly class="api-input" value="<?php echo $api?>.revlastslide();"></td>
						</tr>
						<tr>
							<td class="api-cell1"><?php echo $this->__("External Scroll")?>:</td>
							<td class="api-cell2"><input type="text" readonly class="api-input" value="<?php echo $api?>.revscroll(offset);"></td>
						</tr>
						<tr>
							<td class="api-cell1"><?php echo $this->__("Redraw Slider")?>:</td>
							<td class="api-cell2"><input type="text" readonly  class="api-input" value="<?php echo $api?>.revredraw();"></td>
						</tr>
						<tr>
							<td class="api-cell1"><?php echo $this->__("Kill and Remove Slider")?>:</td>
							<td class="api-cell2"><input type="text" readonly  class="api-input" value="<?php echo $api?>.revkill();"></td>
						</tr>

					</table>
					<div class="divide20"></div>
					<hr>
					<div class="divide20"></div>
					<div class="api-caption"><?php echo $this->__("API Events")?>:</div>
					<div class="divide20"></div>
					<div class="api-desc"><?php echo $this->__("Copy and Paste the Below listed API Functions into your jQuery Functions for Revslider Event Listening")?>.</div>
					<textarea id="api_area" readonly>

<?php echo $api?>.bind("revolution.slide.onloaded",function (e) {
	//alert("slider loaded");
});

<?php echo $api?>.bind("revolution.slide.onchange",function (e,data) {
	//alert("slide changed to: "+data.slideIndex);
	//data.slideIndex <?php echo $this->__('is the index of the li container in this Slider'); ?>

	//data.slide <?php echo $this->__('is the current slide jQuery object (the li element)'); ?>

});

<?php echo $api?>.bind("revolution.slide.onpause",function (e,data) {
	//alert("timer paused");
});

<?php echo $api?>.bind("revolution.slide.onresume",function (e,data) {
	//alert("timer resume");
});

<?php echo $api?>.bind("revolution.slide.onvideoplay",function (e,data) {
	//alert("video play");
});

<?php echo $api?>.bind("revolution.slide.onvideostop",function (e,data) {
	//alert("video stopped");
});

<?php echo $api?>.bind("revolution.slide.onstop",function (e,data) {
	//alert("slider stopped");
});

<?php echo $api?>.bind("revolution.slide.onbeforeswap",function (e) {
	//alert("before swap");
});

<?php echo $api?>.bind("revolution.slide.onafterswap",function (e) {
	//alert("after swap");
});

<?php echo $api?>.bind("revolution.slide.slideatend",function (e) {
	//alert("slide at end");
});


			</textarea>
		</div>
	</div>

	<script type="text/javascript">
		(function(jQuery) {
		jQuery(document).ready(function(){

			RevSliderAdmin.initEditSlideView();
		});
		})($nwd_jQuery);
	</script>
