<?php

/**
 * Nwdthemes Revolution Slider Extension
 *
 * @package     Revslider
 * @author		Nwdthemes <mail@nwdthemes.com>
 * @link		http://nwdthemes.com/
 * @copyright   Copyright (c) 2014. Nwdthemes
 * @license     http://themeforest.net/licenses/terms/regular
 */

?>
	<input type="hidden" id="sliderid" value="<?php echo $sliderID?>"></input>

	<div class="wrap settings_wrap">
		<div class="clear_both"></div>

			<div class="title_line">
				<div id="icon-options-general" class="icon32"></div>
				<?php
				if($sliderTemplate){
					?>
					<div class="view_title"><?php echo $this->__("Edit Slider Template")?></div>
					<?php
					$template_value = 'true';
				}else{
					?>
					<div class="view_title"><?php echo $this->__("Edit Slider")?></div>
					<?php
					$template_value = 'false';
				}
				?>
				<input type="hidden" id="revslider_template" value="<?php echo $template_value; ?>"></input>

				<a href="<?php echo GlobalsRevSlider::LINK_HELP_SLIDER?>" class="button-secondary float_right mtop_10 mleft_10" target="_blank"><?php echo $this->__("Help")?></a>

			</div>

			<div class="settings_panel">

				<div class="settings_panel_left">

					<div id="main_dlier_settings_wrapper" class="postbox unite-postbox ">
					  <h3 class="box-closed"><i style="float:left;margin-top:4px;font-size:14px;" class="eg-icon-cog"></i><span><?php echo $this->__("Main Slider Settings") ?></span></h3>
					  <div class="p10">

							<div class="divide20"></div>

							<a class='button-primary revgreen' href='javascript:void(0)' id="button_save_slider_top" ><i class="revicon-cog"></i><?php echo $this->__("Save Settings")?></a>
							<span id="loader_update_top" class="loader_round" style="display:none;"><?php echo $this->__("updating...")?> </span>
							<span id="update_slider_success_top" class="success_message"></span>
							<a class='button-primary revred' id="button_delete_slider_top"  href='javascript:void(0)'><i class="revicon-trash"></i><?php echo $this->__("Delete Slider")?></a>
							<a class='button-primary revyellow' id="button_close_slider_edit_top"  href='<?php echo $this->helper("adminhtml")->getUrl('adminhtml/nwdrevslider/sliders') ?>' ><i class="revicon-cancel"></i><?php echo $this->__("Close")?></a>
							<a class="button-primary revblue" href="<?php echo $linksEditSlides?>"  id="link_edit_slides_top"><i class="revicon-pencil-1"></i><?php echo $this->__("Edit Slides")?> </a>
							<a class="button-primary revgray" href="javascript:void(0)"  id="button_preview_slider_top" title="<?php echo $this->__("Preview Slider")?>"><i class="revicon-search-1"></i><?php echo $this->__("Preview")?></a>
							<div class="clear"></div>

							<div class="divide20"></div>

							<?php $settingsSliderMain->draw("form_slider_main",true)?>

							<div id="layout-preshow">
								<strong>Layout Example </strong><span style="font-size:11px;font-style:italic;"><?php echo $this->__(" Can be different based on Theme Style")?></span>
								<div class="divide20"></div>
								<div id="layout-preshow-page">
									<div class="layout-preshow-text">BROWSER</div>
									<div id="layout-preshow-theme">
											<div class="layout-preshow-text">PAGE</div>
									</div>
									<div id="layout-preshow-slider">
											<div class="layout-preshow-text">SLIDER</div>
									</div>
									<div id="layout-preshow-grid">
											<div class="layout-preshow-text">LAYERS GRID</div>
									</div>
								</div>
							</div>

							<div class="divide20"></div>

							<a class='button-primary revgreen' href='javascript:void(0)' id="button_save_slider" ><i class="revicon-cog"></i><?php echo $this->__("Save Settings")?></a>
							<span id="loader_update" class="loader_round" style="display:none;"><?php echo $this->__("updating...")?> </span>
							<span id="update_slider_success" class="success_message"></span>
							<a class='button-primary revred' id="button_delete_slider"  href='javascript:void(0)'><i class="revicon-trash"></i><?php echo $this->__("Delete Slider")?></a>
							<a class='button-primary revyellow' id="button_close_slider_edit"  href='<?php echo $this->helper("adminhtml")->getUrl('adminhtml/nwdrevslider/sliders') ?>' ><i class="revicon-cancel"></i><?php echo $this->__("Close")?></a>
							<a class="button-primary revblue" href="<?php echo $linksEditSlides?>"  id="link_edit_slides"><i class="revicon-pencil-1"></i><?php echo $this->__("Edit Slides")?> </a>
							<a class="button-primary revgray" href="javascript:void(0)"  id="button_preview_slider" title="<?php echo $this->__("Preview Slider")?>"><i class="revicon-search-1"></i><?php echo $this->__("Preview")?></a>
							<div class="clear"></div>

							<div class="divide20"></div>
					  </div>
					</div>

					<?php
					$this->getChild('slider_toolbox')->assign('sliderID', $sliderID);
					echo $this->getChildHtml('slider_toolbox');

					$this->getChild('slider_api')->setData('sliderID', $sliderID);
					echo $this->getChildHtml('slider_api');

					$this->getChild('slider_css_js')
						->assign('sliderID', $sliderID)
						->assign('arrFieldsParams', $arrFieldsParams);
					echo $this->getChildHtml('slider_css_js');
					?>

				</div>
				<div class="settings_panel_right">
					<?php $settingsSliderParams->draw("form_slider_params",true); ?>
				</div>

				<div class="clear"></div>

			</div>

	</div>

	<?php echo $this->getChildHtml('dialog_preview_slider'); ?>

	<script type="text/javascript">
		var g_jsonTaxWithCats = <?php echo $jsonTaxWithCats?>;
		var g_sliderTemplate = <?php echo $sliderTemplate ? 'true' : 'false'; ?>;

		(function(jQuery) {
		jQuery(document).ready(function(){
			RevSliderAdmin.initEditSliderView();

			<?php if($sliderTemplate){ ?>
			RevSliderAdmin.initSliderViewTemplate();
			<?php } ?>
		});
		})($nwd_jQuery);


	</script>
