<?php

/**
 * Nwdthemes Revolution Slider Extension
 *
 * @package     Revslider
 * @author		Nwdthemes <mail@nwdthemes.com>
 * @link		http://nwdthemes.com/
 * @copyright   Copyright (c) 2014. Nwdthemes
 * @license     http://themeforest.net/licenses/terms/regular
 */

	// TODO: put this in head maybe
	echo Mage::helper('nwdrevslider')->inlcudeStyleFonts();
	?>
	<?php if($slider->getParam("custom_css", '') !== '') : ?>
		<style type="text/css">
			<?php echo stripslashes($slider->getParam("custom_css", '')); ?>
		</style>
	<?php endif; ?>
	<!--  load good font -->
	<?php

		if($slide->isStaticSlide()){ //insert sliderid for preview
			?>
			<input type="hidden" id="sliderid" value="<?php echo $slider->getID(); ?>" />
			<?php
		}
		?>

	<div class="wrap settings_wrap">
		<div class="clear_both"></div>

		<div class="title_line">
			<div id="icon-options-general" class="icon32"></div>
			<div class="view_title">
				<?php echo $this->__('Slider:'); echo ' '.$slider->getParam("title",""); ?>,
				<?php
				if($sliderTemplate == "true"){
					echo $this->__("Edit Template Slide");
				}else{
					echo $this->__("Edit Slide");
				}
				?> <?php echo $slideOrder?>, <?php echo $this->__("Title:"); ?> <?php echo $slideTitle?>
			</div>

			<a href="<?php echo GlobalsRevSlider::LINK_HELP_SLIDE?>" class="button-primary float_right revblue mtop_10 mleft_10" target="_blank"><?php echo $this->__("Help")?></a>

		</div>

		<div id="slide_selector" class="slide_selector">
			<?php
			$sID = $slider->getID();

			$useStaticLayers = $slider->getParam("enable_static_layers","off");
			if($useStaticLayers == 'on'){
				?>
				<ul class="list_static_slide_links">
					<li class="revgray nowrap">
						<a href="<?php echo $this->getViewUrl(RevSliderAdmin::VIEW_SLIDE,"id=static_$sID"); ?>" class="add_slide"><i class="eg-icon-lock"></i><span><?php echo $this->__("Static Layer")?></span></a>
					</li>
				</ul>
				<?php
			}
			?>
			<ul class="list_slide_links">
				<?php
				foreach($arrSlideNames as $slidelistID=>$c_slide){

					$slideName = $c_slide["name"];
					$title = $c_slide["title"];
					$arrChildrenIDs = $c_slide["arrChildrenIDs"];

					$class = "tipsy_enabled_top";
					$titleclass = "";
					$urlEditSlide = $this->getViewUrl(RevSliderAdmin::VIEW_SLIDE,"id=$slidelistID");
					if($slideID == $slidelistID || in_array($slideID, $arrChildrenIDs)){
						$class .= " selected";
						$titleclass = " slide_title";
						$urlEditSlide = "javascript:void(0)";
					}

					$addParams = "class='".$class."'";
					$slideName = str_replace("'", "", $slideName);

					?>
					<li id="slidelist_item_<?php echo $slidelistID?>">
						<a href="<?php echo $urlEditSlide?>" title='<?php echo $slideName?>' <?php echo $addParams?>><span class="nowrap<?php echo $titleclass?>"><?php echo $title?></span></a>
					</li>
					<?php
				}
				?>
				<li>
					<a id="link_add_slide" href="javascript:void(0);" class="add_slide"><span class="nowrap"><?php echo $this->__("Add Slide")?></span></a>
				</li>
				<li>
					<div id="loader_add_slide" class="loader_round" style="display:none"></div>
				</li>
			</ul>
		</div>

		<div class="clear"></div>
		<!--<hr class="tabdivider">-->

		<div class="divide220"></div>

		<?php
		if(!$slide->isStaticSlide()){
		?>

			<div id="slide_params_holder" class="postbox unite-postbox" style="max-width:100% !important;">
				<h3 class="box-closed tp-accordion"><span class="postbox-arrow2">-</span><span><?php echo $this->__("General Slide Settings") ?></span></h3>
				<div class="toggled-content">
					<form name="form_slide_params" id="form_slide_params">
					<?php
						$settingsSlideOutput->draw("form_slide_params",false);
					?>
						<input type="hidden" id="image_url" name="image_url" value="<?php echo $imageUrl?>" />
						<input type="hidden" id="image_id" name="image_id" value="<?php echo $imageID?>" />
					</form>
				</div>
			</div>

		<?php
		}
		?>

		<div id="jqueryui_error_message" class="unite_error_message" style="display:none;">
				<b>Warning!!! </b>The jquery ui javascript include that is loaded by some of the plugins are custom made and not contain needed components like 'autocomplete' or 'draggable' function.
				Without those functions the editor may not work correctly. Please remove those custom jquery ui includes in order the editor will work correctly.
		 </div>

		<?php
		$this->getChild('edit_layers')
			->assign('slide', $slide)
			->assign('slider', $slider)
			->assign('arrSlideNames', $arrSlideNames)
			->assign('sliderTemplate', $sliderTemplate)
			->assign('arrCustomAnim', $arrCustomAnim)
			->assign('settingsLayerOutput', $settingsLayerOutput)
			->assign('slideDelay', $slideDelay)
			->assign('sliderParams', $sliderParams)
			->assign('bgType', $bgType)
			->assign('slideBGColor', $slideBGColor)
			->assign('divLayersClass', $divLayersClass)
			->assign('bgSolidPickerProps', $bgSolidPickerProps)
			->assign('bgFit', $bgFit)
			->assign('bgFitX', $bgFitX)
			->assign('bgFitY', $bgFitY)
			->assign('bgRepeat', $bgRepeat)
			->assign('bgPosition', $bgPosition)
			->assign('bgPositionX', $bgPositionX)
			->assign('bgPositionY', $bgPositionY)
			->assign('bgEndPosition', $bgEndPosition)
			->assign('bgEndPositionX', $bgEndPositionX)
			->assign('bgEndPositionY', $bgEndPositionY)
			->assign('slideBGExternal', $slideBGExternal)
			->assign('slideBGColor', $slideBGColor)
			->assign('style', $style)
			->assign('jsonLayers', $jsonLayers)
			->assign('jsonCaptions', $jsonCaptions)
			->assign('jsonFontFamilys', $jsonFontFamilys)
			->assign('arrCssStyles', $arrCssStyles)
			->assign('arrButtonClasses', $arrButtonClasses)
			->assign('urlCaptionsCSS', $urlCaptionsCSS)
			->assign('divLayersWidth', $divLayersWidth)
			->assign('divbgminwidth', $divbgminwidth)
			->assign('style_wrapper', $style_wrapper)
			->assign('class_wrapper', $class_wrapper)
			->assign('kenburn_effect', $kenburn_effect)
			->assign('kb_duration', $kb_duration)
			->assign('kb_easing', $kb_easing)
			->assign('kb_start_fit', $kb_start_fit)
			->assign('kb_end_fit', $kb_end_fit);

		echo $this->getChildHtml('edit_layers');
		?>

		<?php
		if(!$slide->isStaticSlide()){
		?>
			<a href="javascript:void(0)" id="button_save_slide" class="revgreen button-primary"><div class="updateicon"></div><?php echo $this->__("Update Slide")?></a>
		<?php }else{ ?>
			<a href="javascript:void(0)" id="button_save_static_slide" class="revgreen button-primary"><div class="updateicon"></div><?php echo $this->__("Update Static Layers")?></a>
		<?php } ?>
		<span id="loader_update" class="loader_round" style="display:none;"><?php echo $this->__("updating")?>...</span>
		<span id="update_slide_success" class="success_message" class="display:none;"></span>
		<a href="<?php echo $this->getViewUrl(RevSliderAdmin::VIEW_SLIDER,"id=$sliderID");?>" class="button-primary revblue"><?php echo $this->__("To Slider Settings")?></a>
		<a id="button_close_slide" href="<?php echo $closeUrl?>" class="button-primary revyellow"><div class="closeicon"></div><?php echo $this->__("To Slide List")?></a>

		<?php
		if(!$slide->isStaticSlide()){
		?>
		<a href="javascript:void(0)" id="button_delete_slide" class="button-primary revred" original-title=""><i class="revicon-trash"></i><?php echo $this->__("Delete Slide")?></a>
		<?php } ?>
	</div>

	<div class="vert_sap"></div>

	<?php
	$this->getChild('dialog_preview_slide')->assign('iframeStyle', $iframeStyle);
	echo $this->getChildHtml('dialog_preview_slide');
	?>

	<?php
	if($slide->isStaticSlide())
		echo $this->getChildHtml('dialog_preview_slider');
	?>

	<?php echo $this->getChildHtml('video_dialog'); ?>

	<!-- FIXED POSITIONED TOOLBOX -->
		<div class="" style="position:fixed;right:-10px;top:148px;z-index:100;">
			<?php
			if(!$slide->isStaticSlide()){
			?>
			<a href="javascript:void(0)" id="button_save_slide-tb" class="revgreen button-primary button-fixed"><div style="font-size:16px; padding:10px 5px;" class="revicon-arrows-ccw"></div></a>
			<?php }else{ ?>
			<a href="javascript:void(0)" id="button_save_static_slide-tb" class="revgreen button-primary button-fixed"><div style="font-size:16px; padding:10px 5px;" class="revicon-arrows-ccw"></div></a>
			<?php } ?>
		</div>

	<div class="" style="position:fixed;right:-10px;top:100px;z-index:100;">

	</div>

	<?php
	if($slide->isStaticSlide()){
		$slideID = $slide->getID();
	}
	?>
	<script type="text/javascript">
		var g_messageDeleteSlide = "<?php echo $this->__("Delete this slide?")?>";
		var g_productImagePlaceholder = "<?php echo $this->getSkinUrl('images/nwdthemes/revslider/dummy/product_image_placeholder.png'); ?>";
		(function(jQuery) {
		jQuery(document).ready(function(){
			RevSliderAdmin.initEditSlideView(<?php echo $slideID?>,<?php echo $sliderID?>);
		});
		})($nwd_jQuery);
	</script>
