<?php

/**
 * Nwdthemes Revolution Slider Extension
 *
 * @package     Revslider
 * @author		Nwdthemes <mail@nwdthemes.com>
 * @link		http://nwdthemes.com/
 * @copyright   Copyright (c) 2014. Nwdthemes
 * @license     http://themeforest.net/licenses/terms/regular
 */

?>
	<div class="postbox box-slideslist">
		<h3>
			<span class='slideslist-title'><?php echo $this->__("Slides List")?></span>
			<span id="saving_indicator" class='slideslist-loading'><?php echo $this->__("Saving Order")?>...</span>
		</h3>
		<div class="inside">
			<?php if(empty($arrSlides)):?>
				<?php echo $this->__("No Slides Found")?>
			<?php endif?>
			<ul id="list_slides" class="list_slides ui-sortable">
				<?php foreach($arrSlides as $index=>$slide):
					$bgType = $slide->getParam("background_type","image");
					$bgFit = $slide->getParam("bg_fit","cover");
					$bgFitX = intval($slide->getParam("bg_fit_x","100"));
					$bgFitY = intval($slide->getParam("bg_fit_y","100"));
					$bgPosition = $slide->getParam("bg_position","center top");
					$bgPositionX = intval($slide->getParam("bg_position_x","0"));
					$bgPositionY = intval($slide->getParam("bg_position_y","0"));
					$bgRepeat = $slide->getParam("bg_repeat","no-repeat");
					$bgStyle = ' ';
					if($bgFit == 'percentage'){
						$bgStyle .= "background-size: ".$bgFitX.'% '.$bgFitY.'%;';
					}else{
						$bgStyle .= "background-size: ".$bgFit.";";
					}
					if($bgPosition == 'percentage'){
						$bgStyle .= "background-position: ".$bgPositionX.'% '.$bgPositionY.'%;';
					}else{
						$bgStyle .= "background-position: ".$bgPosition.";";
					}
					$bgStyle .= "background-repeat: ".$bgRepeat.";";

					$order = $index + 1;

					$urlImageForView = $slide->getUrlImageThumb();
					$slideTitle = $slide->getParam("title","Slide");
					$title = $slideTitle;
					$filename = $slide->getImageFilename();
					$imageAlt = stripslashes($slideTitle);

					if(empty($imageAlt))
						$imageAlt = "slide";

					$postID = $slide->getID();

					$urlEditSlide = $this->helper('adminhtml')->getUrl('adminhtml/catalog_product/edit/id/' . $postID);
					$linkEdit = UniteFunctionsRev::getHtmlLink($urlEditSlide, $title,"","",true);
					?>
					<li id="slidelist_item_<?php echo $postID?>" class="ui-state-default">
						<span class="slide-col col-order">
							<span class="order-text"><?php echo $order?></span>
							<div class="state_loader" style="display:none;"></div>
							<div class="icon_state state_published disabled_control"></div>
						</span>
						<span class="slide-col col-name">
							<div class="slide-title-in-list"><?php echo $linkEdit?></div>
							<a class='button-primary revgreen' href='<?php echo $urlEditSlide?>'><i class="revicon-pencil-1"></i><?php echo $this->__("Edit Product")?></a>
						</span>
						<span class="slide-col col-image">
							<?php if(!empty($urlImageForView)):?>
								<div id="slide_image_<?php echo $postID?>" class="slide_image disabled_control" alt="<?php echo $imageAlt?>" style="background-image:url('<?php echo $urlImageForView?>');<?php echo $bgStyle; ?>"></div>
							<?php else:?>
								no image
							<?php endif?>
						</span>
						<span class="slide-col col-operations-posts">
							<?php if ($showDelete) : ?>
								<a id="button_delete_slide" class='button-primary revred button_delete_slide' data-slideid="<?php echo $postID?>" href='javascript:void(0)'><i class="revicon-trash"></i><?php echo $this->__("Delete")?></a>
							<?php endif; ?>
						</span>
						<?php if ( ! $showSortBy) : ?>
							<span class="slide-col col-handle">
								<div class="col-handle-inside">
									<span class="ui-icon ui-icon-arrowthick-2-n-s"></span>
								</div>
							</span>
						<?php endif; ?>
						<div class="clear"></div>
					</li>
				<?php endforeach;?>
			</ul>
		</div>
	</div>
