<?php

/**
 * Nwdthemes Revolution Slider Extension
 *
 * @package     Revslider
 * @author		Nwdthemes <mail@nwdthemes.com>
 * @link		http://nwdthemes.com/
 * @copyright   Copyright (c) 2014. Nwdthemes
 * @license     http://themeforest.net/licenses/terms/regular
 */

$outputTemplates = $this->outputTemplates;
$no_sliders = $this->no_sliders;
$limit = $this->limit;
$otype = $this->otype;
$arrSliders = $this->arrSliders;
$arrSlidersTemplates = $this->arrSlidersTemplates;

//$limit = 10; // number of rows in page
$total = 0;

if(!$no_sliders){
?>
	<table class='wp-list-table widefat fixed unite_table_items'>
		<thead>
			<tr>
				<th width='20px'><?php echo $this->__("ID")?></th>
				<th width='25%'>
					<?php echo $this->__("Name")?>
					<a href="<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/nwdrevslider/sliders/order/asc/ot/name/type/' . $otype); ?>" class="eg-icon-down-dir"></a>
					<a href="<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/nwdrevslider/sliders/order/desc/ot/name/type/' . $otype); ?>" class="eg-icon-up-dir"></a>
				</th>
				<?php
				if(!$outputTemplates){
				?>
				<th width='180px'>
					<?php echo $this->__("Shortcode")?>
					<a href="<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/nwdrevslider/sliders/order/asc/ot/alias/type/' . $otype); ?>" class="eg-icon-down-dir"></a>
					<a href="<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/nwdrevslider/sliders/order/desc/ot/alias/type/' . $otype); ?>" class="eg-icon-up-dir"></a>
				</th>
				<?php }else{
				?><th width='180px'></th><?php
				} ?>
				<th width='100'><?php echo $this->__("Source")?></th>
				<th width='70px'><?php echo $this->__("N. Slides")?></th>
				<th width='50%'><?php echo $this->__("Actions")?> </th>
			</tr>
		</thead>
		<tbody>
			<?php
			if($outputTemplates){
				$useSliders = $arrSlidersTemplates;
				$pagenum = Mage::app()->getRequest()->getParam('pagenumt', 1);
				$offset = ( $pagenum - 1 ) * $limit;
			}else{
				$useSliders = $arrSliders;
				$pagenum = Mage::app()->getRequest()->getParam('pagenum', 1);
				$offset = ( $pagenum - 1 ) * $limit;
			}

			$cur_offset = 0;
			foreach($useSliders as $slider){
				$errorMessage = '';
				$total++;
				$cur_offset++;
				if($cur_offset <= $offset) continue; //if we are lower then the offset, continue;
				if($cur_offset > $limit + $offset) continue; // if we are higher then the limit + offset, continue

				try{

					$id = $slider->getID();
					$showTitle = $slider->getShowTitle();
					$title = $slider->getTitle();
					$alias = $slider->getAlias();
					$isFromPosts = $slider->isSlidesFromPosts();
					$strSource = $this->__("Gallery");
					$preicon = "revicon-picture-1";

					if($outputTemplates) $strSource = "Template";
					if ($strSource=="Template") $preicon ="templateicon";

					$rowClass = "";
					if($isFromPosts == true){
						$strSource = $this->__("Products");
						$preicon ="revicon-doc";
						$rowClass = "class='row_alt'";
					}

					if($outputTemplates){
						$editLink = Mage::helper("adminhtml")->getUrl('adminhtml/nwdrevslider/slidertemplate/id/' . $id);
					}else{
						$editLink = Mage::helper("adminhtml")->getUrl('adminhtml/nwdrevslider/slider/id/' . $id);
					}
					$editSlidesLink = Mage::helper("adminhtml")->getUrl('adminhtml/nwdrevslider/slides/id/' . $id);
					$exportLink = Mage::helper("adminhtml")->getUrl('adminhtml/nwdrevslider/ajax/client_action/export_slider/dummy/false/sliderid/' . $id);

					$showTitle = UniteFunctionsRev::getHtmlLink($editLink, $showTitle);

					$shortCode = $slider->getShortcode();
					$numSlides = $slider->getNumSlides();

				}catch(Exception $e){
					$errorMessage = "ERROR: ".$e->getMessage();
					$strSource = "";
					$numSlides = "";
				}

				?>
				<tr <?php echo $rowClass?>>
					<td><?php echo $id?><span id="slider_title_<?php echo $id?>" class="hidden"><?php echo $title?></span></td>
					<td>
						<?php echo $showTitle?>
						<?php if(!empty($errorMessage)):?>
							<div class='error_message'><?php echo $errorMessage?></div>
						<?php endif?>
					</td>
					<?php
					if(!$outputTemplates){
					?>
					<td><?php echo $shortCode?></td>
					<?php }else{ ?><td></td><?php } ?>
					<td><?php echo "<i class=".$preicon."></i>".$strSource?></td>
					<td><?php echo $numSlides?></td>
					<td>
						<a class="button-primary revgreen" href='<?php echo $editLink ?>' title=""><i class="revicon-cog"></i><?php echo $this->__("Settings")?></a>
						<a class="button-primary revblue" href='<?php echo $editSlidesLink ?>' title=""><i class="revicon-pencil-1"></i><?php echo $this->__("Edit Slides")?></a>
						<a class="button-primary revcarrot export_slider_overview" data-url="<?php echo $exportLink; ?>" href="javascript:void(0);" title=""><i class="revicon-export"></i><?php echo $this->__("Export Slider")?></a>
						<?php
						$generalSettings = $this->getSettings("general");
						$show_dev_export = $generalSettings->getSettingValue("show_dev_export",'off');
						if($show_dev_export == 'on'){
							?>
							<a class="button-primary revpurple export_slider_standalone" id="export_slider_standalone_<?php echo $id?>" href="javascript:void(0);" title=""><i class="revicon-export"></i><?php echo $this->__("HTML &LT;/&GT;")?></a>
							<?php
						}
						?>
						<a class="button-primary revred button_delete_slider"id="button_delete_<?php echo $id?>" href='javascript:void(0)' title="<?php echo $this->__("Delete")?>"><i class="revicon-trash"></i></a>
						<a class="button-primary revyellow button_duplicate_slider" id="button_duplicate_<?php echo $id?>" href='javascript:void(0)' title="<?php echo $this->__("Duplicate")?>"><i class="revicon-picture"></i></a>
						<div id="button_preview_<?php echo $id?>" class="button_slider_preview button-primary revgray" title="<?php echo $this->__("Preview")?>"><i class="revicon-search-1"></i></div>
					</td>

				</tr>
				<?php
			}
			?>

		</tbody>
	</table>
<?php
}
?>
	<p>
		<div style="float: left;">
			<?php
			if($outputTemplates){
				?>
				<a class='button-primary revblue' href='<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/nwdrevslider/slidertemplate'); ?>'><?php echo $this->__("Create New Template Slider")?> </a>
				<?php
			}else{
				?>
				<a class='button-primary revblue' href='<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/nwdrevslider/slider'); ?>'><?php echo $this->__("Create New Slider")?> </a>
				<?php
			}
			?>
		</div>
		<?php
		if(!$no_sliders){
			$num_of_pages = ceil( $total / $limit );

			if($outputTemplates)
				$param = 'pagenumt';
			else
				$param = 'pagenum';

			$page_links = Mage::helper('nwdrevslider')->paginateLinks( array(
				'base' => 'adminhtml/nwdrevslider/sliders/' . $param . '/%#%/',
				'format' => '',
				'add_args' => array('limit' => $limit),
				'prev_text' => $this->__( '&laquo;' ),
				'next_text' => $this->__( '&raquo;' ),
				'total' => $num_of_pages,
				'current' => $pagenum
			) );

			if ( $page_links ) {
				echo '<div class="rev-pagination-wrap"><div class="tablenav"><div class="tablenav-pages" style="margin: 1em 0">' . $page_links . '</div></div></div>';
			}


			if(!$outputTemplates){
				?>
				<form style="float:left; margin-left:10px">
					<select name="limit" onchange="document.location.href = this.value;">
						<option <?php echo ($limit == 10) ? 'selected="selected"' : ''; ?> value="<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/nwdrevslider/sliders/pagenum/1/limit/10'); ?>">10</option>
						<option <?php echo ($limit == 25) ? 'selected="selected"' : ''; ?> value="<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/nwdrevslider/sliders/pagenum/1/limit/25'); ?>">25</option>
						<option <?php echo ($limit == 50) ? 'selected="selected"' : ''; ?> value="<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/nwdrevslider/sliders/pagenum/1/limit/50'); ?>">50</option>
						<option <?php echo ($limit == 9999) ? 'selected="selected"' : ''; ?> value="<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/nwdrevslider/sliders/pagenum/1/limit/9999'); ?>"><?php echo $this->__('All'); ?></option>
					</select>
				</form>
				<?php
			}else{
				?>
				<form style="float:left; margin-left:10px">
					<select name="limit" onchange="document.location.href = this.value;">
						<option <?php echo ($limit == 10) ? 'selected="selected"' : ''; ?> value="<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/nwdrevslider/sliders/pagenumt/1/limit_t/10'); ?>">10</option>
						<option <?php echo ($limit == 25) ? 'selected="selected"' : ''; ?> value="<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/nwdrevslider/sliders/pagenumt/1/limit_t/25'); ?>">25</option>
						<option <?php echo ($limit == 50) ? 'selected="selected"' : ''; ?> value="<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/nwdrevslider/sliders/pagenumt/1/limit_t/50'); ?>">50</option>
						<option <?php echo ($limit == 9999) ? 'selected="selected"' : ''; ?> value="<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/nwdrevslider/sliders/pagenumt/1/limit_t/9999'); ?>"><?php echo $this->__('All'); ?></option>
					</select>
				</form>
				<?php
			}

		}
		if(!$outputTemplates){
			?>
			<div style="float: right;"><a id="button_import_slider" class='button-primary float_right revgreen' href='javascript:void(0)'><?php echo $this->__("Import Slider")?> </a></div>
			<?php
		}
		?>
		<div style="clear:both; height:10px"></div>
	</p>
