<?php

/**
 * Nwdthemes Revolution Slider Extension
 *
 * @package     Revslider
 * @author		Nwdthemes <mail@nwdthemes.com>
 * @link		http://nwdthemes.com/
 * @copyright   Copyright (c) 2014. Nwdthemes
 * @license     http://themeforest.net/licenses/terms/regular
 */

$generalSettings = $this->getSettings("general");
$includes_globally = $generalSettings->getSettingValue("includes_globally",'on');
$pages_for_includes = $generalSettings->getSettingValue("pages_for_includes",'');
$show_dev_export = $generalSettings->getSettingValue("show_dev_export",'off');
$enable_logs = $generalSettings->getSettingValue("enable_logs",'off');
?>

<div id="dialog_general_settings" title="<?php echo Mage::helper('nwdrevslider')->__("General Settings")?>" style="display:none;" class="wp-core-ui">

	<div class="settings_wrapper unite_settings_wide">
		<form name="form_general_settings" id="form_general_settings">
				<script type="text/javascript">
					g_settingsObj['form_general_settings'] = {}
				</script>
				<table class="form-table">
					<tbody>
						<tr id="includes_globally_row" valign="top">
							<th scope="row">
								<?php echo Mage::helper('nwdrevslider')->__("Include RevSlider libraries globally:"); ?>
							</th>
							<td>
								<span id="includes_globally_wrapper" class="radio_settings_wrapper">
								<div class="radio_inner_wrapper">
									<input type="radio" id="includes_globally_1" value="on" name="includes_globally" <?php Mage::helper('nwdrevslider')->checked($includes_globally, 'on'); ?>>
									<label for="includes_globally_1" style="cursor:pointer;"><?php echo Mage::helper('nwdrevslider')->__("On"); ?></label>
								</div>

								<div class="radio_inner_wrapper">
									<input type="radio" id="includes_globally_2" value="off" name="includes_globally" <?php Mage::helper('nwdrevslider')->checked($includes_globally, 'off'); ?>>
									<label for="includes_globally_2" style="cursor:pointer;"><?php echo Mage::helper('nwdrevslider')->__("Off"); ?></label>
								</div>
								</span>

								<div class="description_container">
									<span class="description"><?php echo Mage::helper('nwdrevslider')->__("ON - Add CSS and JS Files to all pages. </br>Off - CSS and JS Files will be only loaded on specified pages.")?></span>
								</div>
							</td>
						</tr>
						<tr id="pages_for_includes_row" valign="top">
							<th scope="row">
								<?php echo Mage::helper('nwdrevslider')->__("Pages to include RevSlider libraries:"); ?>
							</th>
							<td>
								<input type="text" class="regular-text" id="pages_for_includes" name="pages_for_includes" value="<?php echo $pages_for_includes; ?>">
								<div class="description_container">
									<span class="description"><?php echo Mage::helper('nwdrevslider')->__("Specify the page handles that the front end includes will be included in. Example: cms_page_view,catalog_product_view")?></span>
								</div>
							</td>
						</tr>
						<tr id="show_dev_export_row" valign="top">
							<th scope="row">
								<?php echo Mage::helper('nwdrevslider')->__("Enable Markup Export option:"); ?>
							</th>
							<td>
								<span id="js_to_footer_wrapper" class="radio_settings_wrapper">
									<div class="radio_inner_wrapper">
										<input type="radio" id="show_dev_export_1" value="on" name="show_dev_export" <?php Mage::helper('nwdrevslider')->checked($show_dev_export, 'on'); ?>>
										<label for="show_dev_export_1" style="cursor:pointer;"><?php echo Mage::helper('nwdrevslider')->__("On"); ?></label>
									</div>

									<div class="radio_inner_wrapper">
										<input type="radio" id="show_dev_export_2" value="off" name="show_dev_export" <?php Mage::helper('nwdrevslider')->checked($show_dev_export, 'off'); ?>>
										<label for="show_dev_export_2" style="cursor:pointer;"><?php echo Mage::helper('nwdrevslider')->__("Off"); ?></label>
									</div>
								</span>
								<div class="description_container">
									<span class="description"><?php echo Mage::helper('nwdrevslider')->__("This will enable the option to export the Slider Markups to copy/paste it directly into websites.")?></span>
								</div>
							</td>
						</tr>

						<tr id="use_hammer_js_row" valign="top">
							<th scope="row">
								<?php echo Mage::helper('nwdrevslider')->__("Enable Logs:"); ?>
							</th>
							<td>
								<span id="enable_logs_wrapper" class="radio_settings_wrapper">
									<div class="radio_inner_wrapper">
										<input type="radio" id="enable_logs_1" value="on" name="enable_logs" <?php Mage::helper('nwdrevslider')->checked($enable_logs, 'on'); ?>>
										<label for="enable_logs_1" style="cursor:pointer;"><?php echo Mage::helper('nwdrevslider')->__("On"); ?></label>
									</div>

									<div class="radio_inner_wrapper">
										<input type="radio" id="use_hammer_js_2" value="off" name="enable_logs" <?php Mage::helper('nwdrevslider')->checked($enable_logs, 'off'); ?>>
										<label for="use_hammer_js_2" style="cursor:pointer;"><?php echo Mage::helper('nwdrevslider')->__("Off"); ?></label>
									</div>
								</span>
								<div class="description_container">
									<span class="description"><?php echo Mage::helper('nwdrevslider')->__("Enable console logs for debugging.")?></span>
								</div>
							</td>
						</tr>
				</tbody>
			</table>
		</form>
	</div>
<br>

<a id="button_save_general_settings" class="button-primary" original-title=""><?php echo Mage::helper('nwdrevslider')->__("Update"); ?></a>
<span id="loader_general_settings" class="loader_round mleft_10" style="display: none;"></span>

</div>
