<div class="qs-page-container bodyscan-page">
    <div class="qs-video-bodyscan">
        <div id="qs-video-block" data-vide-bg="video/ocean" data-vide-options="position: 0% 50%">&nbsp;</div>
    </div>
    <div class="qs-background-bodyscan">
        <div class="qs-what-bodyscan">
            <div class="container">
                <div class="qs-what-bodyscan-content">
                    <div class="qs-desc-50">What is body scan?</div>
                    <div class="qs-desc-normal-16">Using completely safe ultra high density technology, our scanners capture millions of <br />points of 3D data which can be used in innumerable ways.</div>
                </div>
            </div>
        </div>
        <div class="qs-why-using-bodyscan">
            <div class="container">
                <div class="qs-intro-why-using-bodyscan">
                    <div class="qs-desc-50">Why body scan?</div>
                    <div class="qs-desc-normal-16">Your body shape and exact measurements can be shared with your trainer, doctor, <br />our custom design team, as well as your tailor for endless ways ways to improve your quality of life.</div>
                </div>
                <div class="qs-col-why-using-bodyscan">
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="qs-col-why-bodyscan-wrapper">
                                <div class="qs-img-why-bodyscan"><img alt="" src="{{media url="wysiwyg/icon_why_bodyscan_1.png"}}" /></div>
                                <div class="qs-title-why-bodyscan">Medical &amp; Aesthetic</div>
                                <div class="qs-desc-normal-16">Your data can be used as a diagnostic tool and shared with your healthcare professional, chiropractors, physical therapists, orthopedics, and even plastic surgeons to assist in your treatment plan.<br /><br /></div>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="qs-col-why-bodyscan-wrapper">
                                <div class="qs-img-why-bodyscan"><img alt="" src="{{media url="wysiwyg/icon_why_bodyscan_2.png"}}" /></div>
                                <div class="qs-title-why-bodyscan">Informed Training</div>
                                <div class="qs-desc-normal-16">This program allows you to interactively calculate the effects of your exercise and diet, as well as evaluate and improve your training and nutrition programs. This is the most accurate "before" and "after" observational tool on the market.</div>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="qs-col-why-bodyscan-wrapper">
                                <div class="qs-img-why-bodyscan"><img alt="" src="{{media url="wysiwyg/icon_why_bodyscan_3.png"}}" /></div>
                                <div class="qs-title-why-bodyscan">Fitness Assessment</div>
                                <div class="qs-desc-normal-16">Understand your body composition including BMI and how it relates to others in your age group. This technology will identify your RMR (resting metabolic rate) and BRM (basal metabolic rate) and advise on your daily caloric intake to meet your fitness goals. Data can also be used to identify potential health risks or abnormalities.<br /><br /></div>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="qs-col-why-bodyscan-wrapper">
                                <div class="qs-img-why-bodyscan"><img alt="" src="{{media url="wysiwyg/icon_why_bodyscan_4.png"}}" /></div>
                                <div class="qs-title-why-bodyscan">Made-To-Measure</div>
                                <div class="qs-desc-normal-16">Clothes are supposed to fit our bodies as individuals. Before "brand-washing" and mass produced garments, our clothes were mostly tailor made. Our technology allows an expedient way to return to perfect fit apparel. We will create your bespoke sport gear, and you will feel the best you've ever felt in our products. You can also share your measurements with tailors word-wide!</div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="qs-button-learn-more"><a href="/customer/schedule">Book Scan</a></div>
            </div>
        </div>
    </div>
    <div class="qs-use-bodyscan">
        <div class="container">
            <div class="qs-desc-50">How to use your body scan</div>
            <div class="qs-col-use-bodyscan">
                <div class="row">
                    <div class="col-md-3 col-xs-6">
                        <div class="qs-col-use-bodyscan">
                            <div class="qs-img-use-bodyscan"><img alt="" src="http://escapevelocitypro.com/media/wysiwyg/icon_body_1.png" /></div>
                            <div class="qs-title-use-bodyscan">Measurements</div>
                            <div class="qs-desc-normal-16">Extract hundreds of measurements. 76% more precise than an expert tailor and way easier.</div>
                        </div>
                    </div>
                    <div class="col-md-3 col-xs-6">
                        <div class="qs-col-use-bodyscan">
                            <div class="qs-img-use-bodyscan"><img alt="" src="http://escapevelocitypro.com/media/wysiwyg/icon_body_2.png" /></div>
                            <div class="qs-title-use-bodyscan">3D Model</div>
                            <div class="qs-desc-normal-16">Rotate, pan, and zoom a full body model from a body scan. Visualize shape and landmarks.</div>
                        </div>
                    </div>
                    <div class="col-md-3 col-xs-6">
                        <div class="qs-col-use-bodyscan">
                            <div class="qs-img-use-bodyscan"><img alt="" src="http://escapevelocitypro.com/media/wysiwyg/icon_body_5.png" /></div>
                            <div class="qs-title-use-bodyscan">Fat Analysis</div>
                            <div class="qs-desc-normal-16">More precise than the gold standard dunk tank or DEXA and absolutely more convenient.</div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="qs-col-use-bodyscan">
                            <div class="qs-img-use-bodyscan"><img alt="" src="http://escapevelocitypro.com/media/wysiwyg/icon_body_4.png" /></div>
                            <div class="qs-title-use-bodyscan">Track Progress</div>
                            <div class="qs-desc-normal-16">Chart your key measurements over time. Keep your clients, patients, or members motivated.</div>
                        </div>
                    </div>
                    <div class="col-md-3 col-xs-6">
                        <div class="qs-col-use-bodyscan">
                            <div class="qs-img-use-bodyscan"><img alt="" src="http://escapevelocitypro.com/media/wysiwyg/icon_body_3.png" /></div>
                            <div class="qs-title-use-bodyscan">Shape Analysis</div>
                            <div class="qs-desc-normal-16">Analyze a subjects profile, silhouette, and waist-to-hip ratio and view any asymmetries in shape.</div>
                        </div>
                    </div>
                    <div class="col-md-3 col-xs-6">
                        <div class="qs-col-use-bodyscan">
                            <div class="qs-img-use-bodyscan"><img alt="" src="http://escapevelocitypro.com/media/wysiwyg/icon_body_6.png" /></div>
                            <div class="qs-title-use-bodyscan">Risk Assessment</div>
                            <div class="qs-desc-normal-16">Track rate of heart disease, high blood presure and certain cancers using measurements of waist circumference, waist-to-hip ratio, and body fat.</div>
                        </div>
                    </div>
                    <div class="col-md-3 col-xs-6">
                        <div class="qs-col-use-bodyscan">
                            <div class="qs-img-use-bodyscan"><img alt="" src="http://escapevelocitypro.com/media/wysiwyg/icon_body_7.png" /></div>
                            <div class="qs-title-use-bodyscan">Goal Setting</div>
                            <div class="qs-desc-normal-16">Meet physical goals by programming desired weight loss or weight gain, daily burn rate, and activity levels.</div>
                        </div>
                    </div>
                    <div class="col-md-3 col-xs-6">
                        <div class="qs-col-use-bodyscan">
                            <div class="qs-img-use-bodyscan"><img alt="" src="http://escapevelocitypro.com/media/wysiwyg/icon_body_8.png" /></div>
                            <div class="qs-title-use-bodyscan">Dashboard</div>
                            <div class="qs-desc-normal-16">View data analytics, set preferences, and manage your account from anywhere in the world.</div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="qs-button-learn-more"><a href="#">Learn More</a></div>
        </div>
    </div>
    <div class="qs-product-bodyscan">
        <div class="container">
            <div class="qs-product-bodyscan-wrapper">
                <div class="qs-desc-50">Body Scan For Your Perfect Fit</div>
                <div class="qs-desc-normal-16">When something fits well, it feels better. When we feel better, we perform better. Take your training to a new level by throwing away the tape measure and size charts, and investing in your perfect fit.</div>
                <div class="qs-button-learn-more"><a href="/customer/schedule">Book Your Scan</a></div>
            </div>
        </div>
    </div>
</div>