<?php
/**
 * Created by PhpStorm.
 * User: tuyennn
 * Date: 6/15/2016
 * Time: 3:01 PM
 */
class QSoft_CustomerMeasure_Model_Resource_Value_Collection extends Mage_Core_Model_Resource_Db_Collection_Abstract {
    public function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->_init('qsoft_customermeasure/value');
    }
}