<?php
/**
 * @category    MT
 * @package     MT_CatalogSlider
 * @copyright   Copyright (C) 2008-2014 MagentoThemes.net. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      MagentoThemes.net
 * @email       support@magentothemes.net
 */
?>
<tr>
    <td class="label"><?php echo $this->getElement()->getLabel() ?></td>
    <td class="grid" style="">
        <table cellspacing="0" class="data border" id="<?php echo $this->getElement()->getHtmlId() ?>">
            <thead>
            <tr class="headings">
                <th></th>
                <th><?php echo Mage::helper('productoptions')->__('Name') ?></th>
                <th><?php echo Mage::helper('productoptions')->__('Description') ?></th>
                <th><?php echo Mage::helper('productoptions')->__('Class html') ?></th>
                <th><?php echo Mage::helper('productoptions')->__('Price') ?></th>
                <th><?php echo Mage::helper('productoptions')->__('Is Default') ?></th>
                <th><?php echo Mage::helper('productoptions')->__('Icon') ?></th>
                <th><?php echo Mage::helper('productoptions')->__('Image Back') ?></th>
                <th><?php echo Mage::helper('productoptions')->__('Image Front') ?></th>
                <th><?php echo Mage::helper('productoptions')->__('Position') ?></th>
                <th><?php echo Mage::helper('productoptions')->__('Delete') ?></th>
            </tr>
            </thead>
            <tbody id="<?php echo $this->getElement()->getHtmlId() ?>_container"></tbody>
            <tfoot>
            <tr>
                <td colspan="9" class="a-right"><?php echo $this->getAddButtonHtml() ?></td>
            </tr>
            </tfoot>
        </table>
    </td>
</tr>
<script type="text/javascript">
    var imageRowTemplate = '<tr id="sliderImage_{{id}}">' +
        '<td><b>{{id}}</b></td>' +
        '<td><span class="op-name"><input type="text" class="input-text required-entry" name="options_name[{{itemId}}]" style="width:98%;" id="option_name_{{id}}" value="{{name}}"/></span></td>' +
        '<td><span class="op-description"><textarea name="option_description[{{itemId}}]">{{description}}</textarea></span></td>' +
        '<td><span class="op-classhtml"><textarea name="option_classhtml[{{itemId}}]">{{classhtml}}</textarea></span></td>' +
        '<td><span class="op-price"><input type="text" class="input-text validate-number" name="option_price[{{itemId}}]" style="width:98%;" id="option_price_{{id}}" value="{{price}}"/></span></td>' +
        '<td><span class="op-is-default"><input class="" type="radio" {{checked}} name="option_is_default" style="width:98%;" id="option_is_default_{{id}}" value="{{itemId}}"/></span></td>' +
        '<td><span class="preview_icon">{{preview_icon}}</span><input onchange="window.catalogSlider.change(this,\'preview_icon\', \'option_icon_{{id}}\')" type="hidden" class="input-text " name="option_icon_[{{itemId}}]" style="width:98%;" id="option_icon_{{id}}" value="{{icon}}"/>' +
        '<button class="button" type="button" onclick="MT.MediabrowserUtility.openDialog(\'<?php echo Mage::getSingleton('adminhtml/url')->getUrl('adminhtml/cms_wysiwyg_images/index')?>static_urls_allowed/1/target_element_id/option_icon_{{id}}\')"><span><?php echo $this->__('Select')?></span></button></td>' +
        '<td><span class="preview_image_back">{{preview_image_back}}</span><input onchange="window.catalogSlider.change(this,\'preview_image_back\', \'option_image_back_{{id}}\')" type="hidden" class="input-text " name="option_image_back_[{{itemId}}]" style="width:98%;" id="option_image_back_{{id}}" value="{{image_back}}"/>' +
        '<button class="button" type="button" onclick="MT.MediabrowserUtility.openDialog(\'<?php echo Mage::getSingleton('adminhtml/url')->getUrl('adminhtml/cms_wysiwyg_images/index')?>static_urls_allowed/1/target_element_id/option_image_back_{{id}}\')"><span><?php echo $this->__('Select')?></span></button></td>' +
        '<td><span class="preview_image_front">{{preview_image_front}}</span><input onchange="window.catalogSlider.change(this,\'preview_image_front\', \'option_image_front_{{id}}\')" type="hidden" class="input-text " name="option_image_front_[{{itemId}}]" style="width:98%;" id="option_image_front_{{id}}" value="{{image_front}}"/>' +
        '<button class="button" type="button" onclick="MT.MediabrowserUtility.openDialog(\'<?php echo Mage::getSingleton('adminhtml/url')->getUrl('adminhtml/cms_wysiwyg_images/index')?>static_urls_allowed/1/target_element_id/option_image_front_{{id}}\')"><span><?php echo $this->__('Select')?></span></button></td>' +
        '<td><input type="text" class="input-text validate-number" name="option_position[{{itemId}}]" style="width:98%;" id="option_position_{{id}}" value="{{position}}"/></td>' +
        '<td class="a-center"><?php echo $this->getDeleteButtonHtml()?></td>' +
        '</tr>';

    window.catalogSlider = {
        baseUrl: '<?php echo Mage::getBaseUrl('media')?>',
        template: new Template(imageRowTemplate, new RegExp('(^|.|\\r|\\n)({{\\s*(\\w+)\\s*}})', "")),
        itemsCount: 0,
        container: $('<?php echo $this->getElement()->getHtmlId() ?>_container'),
        add: function ( itemId, name, description, classhtml, price, icon, image_front, image_back, position, checked) {
            var id = ++this.itemsCount;
            var randId = randomString(15);
            var data = {
                preview_icon: icon ? this.renderPreview(icon,'preview_icon','option_icon_'+id) : '',
                preview_image_front: image_front ? this.renderPreview(image_front, 'preview_image_front','option_image_front_'+id) : '',
                preview_image_back: image_back ? this.renderPreview(image_back, 'preview_image_back','option_image_back_'+id) : '',
                name: Base64.decode(name) || '',
                description: Base64.decode(description) || '',
                classhtml: classhtml || '',
                price: price || '',
                icon: icon || '',
                image_front: image_front || '',
                image_back: image_back || '',
                position: position || '',
                itemId: itemId || randId,
                id: id,
                checked: checked || ''
            };
            this.container.insert({bottom: this.template.evaluate(data)});
        },
        remove: function (id) {
            var tr = this.container.down('tr#sliderImage_' + id);
            if (tr) tr.remove();
        },
        change: function (elm,className,inputId) {
            var uri = $(elm).value,
                preview = $(elm).up('tr').down('span.'+className);

            if (preview) {
                $(preview).update(this.renderPreview(uri, className,inputId));
            }
        },
        delete: function (elm, className, inputId) {
            if (window.confirm("<?php echo Mage::helper('catalog')->__('Are you sure?'); ?>")) {
                document.getElementById(inputId).value = '';
                preview = $(elm).up('tr').down('span.'+className);
                $(preview).innerHTML = '';

            }
        },
        renderPreview: function (uri, className, inputId) {
            return '<img src="' + uri + '" width="100px"/><span class="del_img" onclick="window.catalogSlider.delete(this,\''+className+'\',\''+inputId+'\');">x</span>';
        }
    };
    function randomString(len) {
        var charSet = '0123456789';
        var randomString = '';
        for (var i = 0; i < len; i++) {
            var randomPoz = Math.floor(Math.random() * charSet.length);
            randomString += charSet.substring(randomPoz, randomPoz + 1);
        }
        return randomString;
    }
    var Base64 = {
        _keyStr: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",
        encode: function (e) {
            if(typeof(e)!='undefined'){
                var t = "";
                var n, r, i, s, o, u, a;
                var f = 0;
                e = Base64._utf8_encode(e);
                while (f < e.length) {
                    n = e.charCodeAt(f++);
                    r = e.charCodeAt(f++);
                    i = e.charCodeAt(f++);
                    s = n >> 2;
                    o = (n & 3) << 4 | r >> 4;
                    u = (r & 15) << 2 | i >> 6;
                    a = i & 63;
                    if (isNaN(r)) {
                        u = a = 64
                    } else if (isNaN(i)) {
                        a = 64
                    }
                    t = t + this._keyStr.charAt(s) + this._keyStr.charAt(o) + this._keyStr.charAt(u) + this._keyStr.charAt(a)
                }
                return t
            }

        }, decode: function (e) {
            if(typeof(e)!='undefined'){
                var t = "";
                var n, r, i;
                var s, o, u, a;
                var f = 0;
                e = e.replace(/[^A-Za-z0-9\+\/\=]/g, "");
                while (f < e.length) {
                    s = this._keyStr.indexOf(e.charAt(f++));
                    o = this._keyStr.indexOf(e.charAt(f++));
                    u = this._keyStr.indexOf(e.charAt(f++));
                    a = this._keyStr.indexOf(e.charAt(f++));
                    n = s << 2 | o >> 4;
                    r = (o & 15) << 4 | u >> 2;
                    i = (u & 3) << 6 | a;
                    t = t + String.fromCharCode(n);
                    if (u != 64) {
                        t = t + String.fromCharCode(r)
                    }
                    if (a != 64) {
                        t = t + String.fromCharCode(i)
                    }
                }
                t = Base64._utf8_decode(t);
                return t
            }

        }, _utf8_encode: function (e) {
            e = e.replace(/\r\n/g, "\n");
            var t = "";
            for (var n = 0; n < e.length; n++) {
                var r = e.charCodeAt(n);
                if (r < 128) {
                    t += String.fromCharCode(r)
                } else if (r > 127 && r < 2048) {
                    t += String.fromCharCode(r >> 6 | 192);
                    t += String.fromCharCode(r & 63 | 128)
                } else {
                    t += String.fromCharCode(r >> 12 | 224);
                    t += String.fromCharCode(r >> 6 & 63 | 128);
                    t += String.fromCharCode(r & 63 | 128)
                }
            }
            return t
        }, _utf8_decode: function (e) {
            var t = "";
            var n = 0;
            var r = c1 = c2 = 0;
            while (n < e.length) {
                r = e.charCodeAt(n);
                if (r < 128) {
                    t += String.fromCharCode(r);
                    n++
                } else if (r > 191 && r < 224) {
                    c2 = e.charCodeAt(n + 1);
                    t += String.fromCharCode((r & 31) << 6 | c2 & 63);
                    n += 2
                } else {
                    c2 = e.charCodeAt(n + 1);
                    c3 = e.charCodeAt(n + 2);
                    t += String.fromCharCode((r & 15) << 12 | (c2 & 63) << 6 | c3 & 63);
                    n += 3
                }
            }
            return t
        }
    };

    <?php foreach ($this->getItems() as $item):?>
    window.catalogSlider.add('<?php echo $item['id']?>', '<?php echo base64_encode($item['name'])?>', '<?php echo base64_encode($item['description'])?>','<?php echo $item['classhtml']?>', '<?php echo $item['price']?>', '<?php echo $item['icon']?>', '<?php echo $item['image_front']?>', '<?php echo $item['image_back']?>', '<?php echo $item['position']?>', '<?php echo $item['checked']?>');
    <?php endforeach ?>
</script>

<style type="text/css">


     span.del_img {
        color: red;
        cursor: pointer;
        display: block;
        font-weight: 700;
        height: 10px;
        position: absolute;
        right: -10px;
        top: 0;
         cursor: pointer;
        width: 10px;
         padding: 0 4px 10px 7px;
         font-weight: bold;
         border: 1px solid red;
         border-radius: 10px;
    }
     span.del_img:hover {
         border: 2px solid blue;
         background: green;
     }

     .preview_icon, .preview_image_back, .preview_image_front {
         display: inline-block;
         position: relative;
     }
</style>