<?php
?>
<div class="qsoft-socialconnect-account">
    <div class="page-title">
        <h1><?php echo $this->__('Vk Connect') ?></h1>
    </div>

    <?php if($this->_hasData()): ?>

    <?php
        $facebookId = $this->_getVkId();
        $status = $this->_getStatus();
        $email = $this->_getEmail();
        $name = $this->_getName();
        $picture = $this->_getPicture();
        $gender = $this->_getGender();
        $birthday = $this->_getBirthday();
    ?>

    <div class="col3-set">
        <div class="box">
            <div class="box-content">
                <div class="col-1">
                    <?php if(!empty($picture)): ?>
                    <p>
                        <img src="<?php echo $picture; ?>" alt="<?php echo $this->escapeHtml($name); ?>" />
                    </p>
                    <?php endif; ?>
                </div>
                <div class="col-2">
                    <?php if(!empty($status)): ?>
                    <p>
                        <?php printf($this->__('Connected as %s', '<strong>'.$status.'</strong>')) ?>
                    </p>
                    <?php endif; ?>
                    <?php if(!empty($email)): ?>
                    <p>
                        <?php printf($this->__('Email: %s', '<strong>'.$email.'</strong>')) ?>
                    </p>
                    <?php endif; ?>
                    <?php if(!empty($facebookId)): ?>
                    <p>
                        <?php printf($this->__('Vk #: %s', '<strong>'.$facebookId.'</strong>')) ?>
                    </p>
                    <?php endif; ?>
                    <?php if(!empty($gender)): ?>
                    <p>
                        <?php printf($this->__('Gender: %s', '<strong>'.$gender.'</strong>')) ?>
                    </p>
                    <?php endif; ?>
                    <?php if(!empty($birthday)): ?>
                    <p>
                        <?php printf($this->__('Birthday: %s', '<strong>'.$birthday.'</strong>')) ?>
                    </p>
                    <?php endif; ?>
                </div>
                <div class="col-3">
                    <?php echo $this->getChildHtml('qsoft_socialconnect_account_vk_button'); ?>
                </div>
            </div>
        </div>
    </div>
    <?php else: ?>
    <div class="col2-set">
        <div class="box-content">
            <div class="col-1">
                <p>
                    <?php echo $this->__('You can connect store account with your Vk account so you could login easier in the future.') ?>
                </p>
            </div>
            <div class="col-2">
                <?php echo $this->getChildHtml('qsoft_socialconnect_account_vk_button'); ?>
            </div>
        </div>
    </div>
    <?php endif; ?>
</div>
