<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php $post = $this->getPost() ?>
<div class="post-list-item">
	<?php echo $this->getBeforePostContentHtml() ?>
	<div class="post-entry entry<?php if ($post->getFeaturedImage()): ?> post-entry-with-image<?php endif; ?>">
		<?php if ($post->isViewableForVisitor()): ?>
			<div class="row">
				<div class="col-sm-4">
					<?php if ($featuredImage = $post->getFeaturedImage()): ?>
						<div class="featured-image left">
							<a href="<?php echo $post->getPermalink() ?>" title="<?php echo $this->escapeHtml($post->getPostTitle()) ?>"><img src="<?php echo $featuredImage->getMediumImage() ?>" alt="<?php echo $this->escapeHtml($post->getPostTitle()) ?>"/></a>
						</div>
					<?php endif; ?>
				</div>
				<div class="col-sm-8">
					<h2><a href="<?php echo $post->getPermalink() ?>" title="<?php echo $this->escapeHtml($post->getPostTitle()) ?>"><?php echo $this->escapeHtml($post->getPostTitle()) ?></a></h2>
					<div class="content-post-entry">
						<?php if ($this->displayExcerptInFeed() || $post->hasMoreTag()): ?>
							<?php echo $post->getPostExcerpt(60) . ' <a href="'.$post->getPermalink().'" title="'.$this->escapeHtml($post->getPostTitle()).'">[Read more]</a>'; ?>
						<?php else: ?>
							<?php //echo $post->getPostContent() ?>
							<?php echo $post->getPostExcerpt(60) . ' <a href="'.$post->getPermalink().'" title="'.$this->escapeHtml($post->getPostTitle()).'">[Read more]</a>'; ?>
						<?php endif; ?>
					</div>
				</div>
			</div>
		<?php else: ?>
			<?php echo $this->getPasswordProtectHtml($post) ?>
		<?php endif; ?>
	</div>
	<?php echo $this->getAfterPostContentHtml() ?>
</div>