<?php

/**
 * Created by PhpStorm.
 * User: tuyennn
 * Date: 6/15/2016
 * Time: 2:58 PM
 */
class QSoft_CustomerMeasure_Model_Value extends Mage_Core_Model_Abstract
{
    public function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->_init('qsoft_customermeasure/value');
    }
}