<?php
$product = $this->getProduct();
$inspireme = $this->getInspireme();
$options = $this->getOptions();
$colorGroup = explode(',', Mage::getStoreConfig('productdesign/group_type/color'));
$groupsDesign = $this->helper('productdesign')->getProductGroupDesign($product);
?>
 opConfigDesign = <?php echo $this->helper('productdesign')->getJsonConfigDesign($options) ?>;
 opGroupDesign = <?php echo Mage::helper('core')->jsonEncode($groupsDesign) ?>;

