<?php if (Mage::getStoreConfig('megamenu/general/enable')): ?>
<?php
$store = Mage::app()->getStore();
$data = Mage::getStoreConfig('megamenu',$store);
$top = $data['top_menu'];
$mobile = $data['mobile_menu'];
$left = $data['left_menu'];
?>
<style>
    /* ------ Top menu -----------*/
<?php if($top['topmenu_align']==1):?>
.ms-topmenu .ms-level0{
    float:right;
}
.ms-topmenu .ms-label{
    float:right;
}
.ms-topmenu{
    text-align:right;
}
.ms-topmenu .col-sub{right:150px;left:auto;}
.ms-megamenu .ms-topmenu .ms-category-level .parent .small{float:left;}
.ms-megamenu .ms-topmenu .ms-category-level .parent .small.glyphicon-chevron-right:before{content: "\e079";}
.ms-topmenu .ms-category-dynamic .col-level .col-xs-12.form-group{padding-right: 10px;}
.ms-topmenu small.glyphicon.glyphicon-th-large{display:none;}
<?php elseif($top['topmenu_align']==2):?>
.ms-megamenu .ms-topmenu {
    display: -moz-box;
    display: -ms-flexbox;
    display: -webkit-flex;
    display: flex;
    flex-direction: row;
    -ms-flex-pack: justify;
    -webkit-justify-content: space-between;
    justify-content: space-between;
    text-align:left;
}
.ms-topmenu .ms-level0{
    -webkit-box-flex: 1;
    -moz-box-flex: 1;
    -ms-box-flex: 1;
}
<?php else: ?>
.ms-megamenu .ms-topmenu{text-align:left;}
.ms-topmenu .ms-label{
    float:left;
}
.ms-topmenu .ms-level0{float: left;}
<?php endif; ?>
.ms-megamenu .ms-topmenu{
    background: #<?php echo $top['menu_background'] ?>;
}
.ms-topmenu .ms-label{
    font-size:<?php echo $top['menu_item_size'] ?>px;
    text-transform:<?php echo $top['menu_item_transform'] ?>;
    color:#<?php echo $top['menu_item_color'] ?>;
    padding:<?php echo ($top['menu_item_height'] - $top['menu_item_size']*1.5)/2 ?>px 15px;
}
.ms-topmenu .ms-label .ms-iconmega{
    height:<?php echo $top['menu_item_size'] ?>px;
    top:<?php echo $top['menu_item_size']/4 ?>px;
}
.ms-topmenu .ms-level0.active .ms-label,
.ms-topmenu .ms-level0:hover .ms-label,
.ms-topmenu .ms-level0:active .ms-label,
.ms-topmenu .ms-level0:focus .ms-label{
    color:#<?php echo $top['menu_item_active_color'] ?>;
}
.ms-topmenu .ms-level0.active,
.ms-topmenu .ms-level0:hover,
.ms-topmenu .ms-level0:active,
.ms-topmenu .ms-level0:focus{
    background-color:#<?php echo $top['menu_item_active_background'] ?>;
}
.ms-topmenu .ms-submenu,.ms-topmenu .col-sub{
    background-color:#<?php echo $top['submenu_background'] ?>;
    color:#<?php echo $top['submenu_main_color'] ?>;
}
.ms-topmenu .ms-submenu a{
    color:#<?php echo $top['submenu_link_color'] ?>;
}
.ms-topmenu .ms-boxtitle{
    color:#<?php echo $top['submenu_boxtitle_color'] ?>;
}
.ms-topmenu .col-category .sub-level3{
    background-color:#<?php echo $top['subcategory_background_color'] ?>;
}
/* ------Left Menu ------*/
.ms-megamenu .ms-leftmenu{
    
}
.ms-leftmenu .msl-label{
    font-size:<?php echo $left['menu_item_size'] ?>px;
    text-transform:<?php echo $left['menu_item_transform'] ?>;
    color:#<?php echo $left['menu_item_color'] ?>;
    background: #<?php echo $left['menu_background'] ?>;
}
.ms-leftmenu .msl-label .ms-iconmega{
    height:<?php echo $left['menu_item_size'] ?>px;
    top:<?php echo $left['menu_item_size']/4 ?>px;
}
.ms-leftmenu .msl-level0.active .msl-label,
.ms-leftmenu .msl-level0:hover .msl-label,
.ms-leftmenu .msl-level0:active .msl-label,
.ms-leftmenu .msl-level0:focus .msl-label{
    color:#<?php echo $left['menu_item_active_color'] ?>;
    background-color:#<?php echo $left['menu_item_active_background'] ?>;
}
.ms-leftmenu .msl-level0.active,
.ms-leftmenu .msl-level0:hover,
.ms-leftmenu .msl-level0:active,
.ms-leftmenu .msl-level0:focus{
    
}
.ms-leftmenu .msl-submenu,.ms-leftmenu .col-sub{
    background-color:#<?php echo $left['submenu_background'] ?>;
    color:#<?php echo $left['submenu_main_color'] ?>;
}
.ms-leftmenu .msl-submenu a{
    color:#<?php echo $left['submenu_link_color'] ?>;
}
.ms-leftmenu .ms-boxtitle{
    color:#<?php echo $left['submenu_boxtitle_color'] ?>;
}
.ms-leftmenu .col-category .sub-level3{
    background-color:#<?php echo $left['subcategory_background_color'] ?>;
}
/* ---- Mobile version ---------*/
.mb-version .anchor_mbmenu,
.mb-version .mb-label.mb-return,
.mb-version .anchor_lmbmenu,
.mb-version .lmb-label.lmb-return{
    background-color:#<?php echo $mobile['anchor_background'] ?>;
}
.mb-version .anchor_mbmenu .anchor_mbmenu_text,
.mb-version .mb-label.mb-return,
.ms-megamenu .anchor_lmbmenu .anchor_lmbmenu_text,
.ms-megamenu .lmb-label.lmb-return{
    color:#<?php echo $mobile['anchor_color'] ?>;
}
.mb-version  .mb-label,
.mb-version  .lmb-label{
    font-size:<?php echo $mobile['mobile_item_size'] ?>px;
    text-transform:<?php echo $mobile['mobile_item_transform'] ?>;
    background-color:#<?php echo $mobile['mobile_item_background'] ?>;
    color:#<?php echo $mobile['mobile_item_color'] ?>;
}
.mb-version  .mb-label.flag,
.mb-version  .lmb-label.flag{
    background-color:#<?php echo $mobile['mobile_item_active_background'] ?>;
}
.mb-version  .mb-submenu,
.mb-version  .lmb-submenu{
    background-color:#<?php echo $mobile['mobile_submenu_background'] ?>;
    color:#<?php echo $mobile['mobile_submenu_main_color'] ?>;
}
.mb-version  .ms-boxtitle{
    color:#<?php echo $mobile['submenu_boxtitle_color'] ?>;
}
.mb-version  .mb-submenu a,
.mb-version  .lmb-submenu a{
    color:#<?php echo $mobile['mobile_submenu_link_color'] ?>;
}
</style>
<?php endif; ?>