<?php
/**
 * author Blanka
 * */
?>
<?php
    $sumenu = $this->getCollection();
    $store = Mage::app()->getStore();
    $effect = Mage::getStoreConfig('megamenu/general/menu_effect', $store);
    $typemenu = Mage::getStoreConfig('megamenu/general/menu_type_config', $store);
    $mobile_effect = Mage::getStoreConfig('megamenu/mobile_menu/mobile_effect', $store);
    if (!Mage::getStoreConfig('megamenu/top_menu/menu_width_main', $store)) {
        $threshold = "779";
    } else {
        $threshold = Mage::getStoreConfig('megamenu/top_menu/menu_width_main', $store);
    }
    $array_width = $this->getSubmenuWidth();
?>   
    <?php if($typemenu !=1): ?>
    <div class="qs-nav-wrapper megamenu-pc ms-megamenu">
        <ul id="ms-topmenu" class="qs-topmenu">
            <?php foreach ($sumenu as $su): ?>
                
                <?php
                $template = $su->getTemplateFilename();
                $block = $this->getLayout()
                        ->createBlock('megamenu/item')
                        ->setData('menu_item', $su->getData())
                        ->setItem($su)
                        ->setArea('frontend')
                        ->setTemplate('megamenu/templates/'. $template);
                ?>   
                <?php if ($su->getMenuType() == 6):?>
                 <li class="ms-level0 nav-<?php echo $su->getId();?> anchor_text"  id="nav-<?php echo $su->getId();?>">
                    <a class="ms-label" href="<?php echo $su->getLink(); ?>" >
                        <?php if($su->getItemIcon()&&Mage::getStoreConfig('megamenu/top_menu/topmenu_align',$store) != 1):?><img class="ms-iconmega" draggable="false" src="<?php echo Mage::getBaseUrl('media')  . '/' . $su->getItemIcon() ?>"/>&nbsp;<?php endif; ?>
                        <?php echo $su->getNameMenu()?>
                        <?php if($su->getItemIcon()&&Mage::getStoreConfig('megamenu/top_menu/topmenu_align',$store) == 1):?>&nbsp;<img class="ms-iconmega" draggable="false" src="<?php echo Mage::getBaseUrl('media')  . '/' . $su->getItemIcon() ?>"/><?php endif; ?>
                    </a>
		</li>   
                <?php else: ?>
                <li class="ms-level0 nav-<?php echo $su->getId(); ?>" id="nav-<?php echo $su->getId(); ?>">  
                    <a class="ms-label ms-hassubmenu" <?php if($effect!=3&&$su->getLink()):?> href="<?php echo $su->getLink();?>"<?php endif; ?>>
                        <?php if($su->getItemIcon()&&Mage::getStoreConfig('megamenu/top_menu/topmenu_align',$store) != 1):?><img class="ms-iconmega" draggable="false" src="<?php echo Mage::getBaseUrl('media')  . '/' . $su->getItemIcon() ?>"/>&nbsp;<?php endif; ?>
                        <?php echo $su->getNameMenu() ?>
                        <?php if($su->getItemIcon()&&Mage::getStoreConfig('megamenu/top_menu/topmenu_align',$store) == 1):?>&nbsp;<img class="ms-iconmega" draggable="false" src="<?php echo Mage::getBaseUrl('media')  . '/' . $su->getItemIcon() ?>"/><?php endif; ?>
                    </a>
                    <div class="ms-submenu col-xs-12 <?php echo Mage::helper('megamenu')->positionSubAuto($su->getSubmenuAlign()); ?>" id="submenu-<?php echo $su->getId(); ?>">
                        <?php  //Zend_debug::dump($su->getData());die(); ?>
                        <?php if($su->getHeader()): ?>
                        <div class="ms-header"><?php echo $su->getHeader(); ?></div>
                        <?php endif;?>   
                        <div class="ms-content">
                          <div class="ms-maincontent" <?php if($su->getFeaturedType() != 0):?>style="float:left;width:<?php echo 100-$su->getFeaturedWidth(); ?>%;<?php if($su->getFeaturedWidth()==100): ?>display:none;<?php endif; ?>"<?php endif;?>><?php echo $block->toHtml() ?></div>
                          <?php if($su->getFeaturedType() != 0 && $su->getMenuType() != 8 ): ?>
                          <div class="ms-featured"style="float:right;width:<?php echo $su->getFeaturedWidth(); ?>%;<?php if($su->getFeaturedWidth()==0): ?>display:none;<?php endif; ?>">
                              <?php echo $block->setTemplate('megamenu/templates/featured/featured.phtml')->toHtml() ;?>
                          </div>
                          <?php endif; ?>
                        </div>
                        <?php if($su->getFooter()): ?>
                        <div class="ms-footer"><?php echo $su->getFooter(); ?></div>
                        <?php endif;?>
                    </div>	
                </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div>
    <?php endif; ?>
    <!-- For Mobile-->
    <?php if($typemenu !=0): ?>

    <div id="mb-menu-version" class="megamenu-mobile ms-megamenu mb-version"<?php if($typemenu==1): ?>style="display:block"<?php endif;?>>
        <div id="mb-topmenu" class="mb-topmenu">
            <?php foreach ($sumenu as $su): ?>

                <?php
                $template = $su->getTemplateFilenameforMobile();
                $block = $this->getLayout()
                    ->createBlock('megamenu/item')
                    ->setData('menu_item', $su->getData())
                    ->setItem($su)
                    ->setArea('frontend')
                    ->setTemplate('megamenu/templates/'. $template);
                ?>
                <?php if ($su->getMenuType() == 6):?>
                    <div class="mb-level0  nav-<?php echo $su->getId();?> anchor_text"  id="mbnav-<?php echo $su->getId();?>">
                        <a class="mb-label col-xs-12" href="<?php echo $su->getLink(); ?>" ><?php echo $su->getNameMenu()?></a>
                    </div>
                <?php else: ?>
                    <div class="mb-level0 nav-<?php echo $su->getId(); ?>" id="nav-<?php echo $su->getId(); ?>">
                        <a class="mb-label mb-click col-xs-12 text-left"  ><?php echo $su->getNameMenu() ?></a>
                        <div class="mb-submenu<?php if($mobile_effect): ?> blind<?php else: ?> slide<?php endif ?>" id="submenu-<?php echo $su->getId(); ?>">
                            <?php if(!$mobile_effect): ?>
                                <a class="mb-label mb-return col-xs-12 text-center"><?php echo $su->getNameMenu() ?></a>
                            <?php endif;?>
                            <div class="mb-submain col-xs-12">
                                <?php if($su->getHeader()): ?>
                                    <div class="mb-header col-xs-12"><?php echo $su->getHeader(); ?></div>
                                    <div class="col-sm-12 form-group"></div>
                                <?php endif;?>
                                <div class="mb-content form-group">
                                    <div class="mb-maincontent <?php if($su->getMenuType() != 8):?> col-md-<?php echo 12-floor(12*$su->getFeaturedWidth()/100) ?><?php endif;?> col-sm-12 col-xs-12"<?php if($su->getFeaturedWidth()== 100): ?>style="display:none;"<?php endif; ?>><?php echo $block->toHtml() ?></div>
                                    <?php if($su->getFeaturedType() != 0): ?>
                                        <div class="hidden-lg hidden-md hidden-sm col-xs-12 form-group"></div>
                                        <div class="mb-featured col-md-<?php echo floor(12*$su->getFeaturedWidth()/100) ?> col-xs-12 hidden-sm hidden-xs"<?php if($su->getFeaturedWidth()== 0): ?>style="display:none;"<?php endif; ?>>
                                            <?php echo $block->setTemplate('megamenu/templates/featured/featured.phtml')->toHtml() ;?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                                <?php if($su->getFooter()): ?>
                                    <div class="col-sm-12 form-group"></div>
                                    <div class="mb-footer col-xs-12"><?php echo $su->getFooter(); ?></div>
                                <?php endif;?>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>
    </div>

    <?php endif;?>
   <script>
        /*-- init variable --*/
        var topmenu = null;
        var mbmenu = null;
        var arr_width =[];
        var $mega = jQuery.noConflict();
        var type_menu = parseInt('<?php echo $typemenu;?>');
        var topmenu_effect = parseInt('<?php echo $effect; ?>');
        var width_change = parseInt('<?php echo $threshold ?>');
        var mobile_effect = parseInt('<?php echo $mobile_effect; ?>');
        var isMobile = navigator.userAgent.match(/iPhone|iPad|iPod/i) || navigator.userAgent.match(/Android/i) || navigator.userAgent.match(/BlackBerry/i) || navigator.userAgent.match(/Opera Mini/i) || navigator.userAgent.match(/IEMobile/i);
        if(type_menu != 1){
            var pc_megamenu = $mega('.megamenu-pc')
            topmenu = $mega('#ms-topmenu');
            var label = $mega('#ms-topmenu .ms-label');
            var label_hassub = $mega('#ms-topmenu .ms-hassubmenu');
            var ms_level0 = $mega('#ms-topmenu .ms-level0');
            var sub_left = $mega('#ms-topmenu .sub_left');
            var sub_right = $mega('#ms-topmenu .sub_right');
            <?php for($i=0;$i<count($array_width);$i++){?>
                arr_width['<?php echo $i ?>']=parseInt('<?php echo $array_width[$i] ?>');
            <?php } ?>
        }
        if(type_menu != 0){
            var mb_megamenu = $mega('.megamenu-mobile');
            mbmenu = $mega('#mb-topmenu');
            var mclick = $mega('#mb-topmenu .mb-click');
            var mreturn = $mega('#mb-topmenu .mb-return');
            var anchor = $mega('.anchor_mbmenu .anchor_mbmenu_text');
        }

//        var jPM = jQuery.jPanelMenu({
//            menu: '#mb-menu-version',
//            trigger: '#mobile-menu'
//        });
//        jPM.on();
    </script>
