<div id="co-billing-form">
    <h3 class="opc-title-block"><i class="qs-icon-opc qs-icon-billing"></i><?php echo $this->__('Billing Address')?></h3>
    <div class="form-list">
    <?php if ($this->customerHasAddresses()): ?>
        <div class="field">
            <label for="billing-address-select" class="notice"><?php echo $this->__('Select a billing address from your address book or enter a new address.') ?></label>
            <div class="input-box">
                <?php echo $this->getAddressesHtmlSelect('billing') ?>
            </div>
        </div>
    <?php endif; ?>
    <div id="billing-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif; ?>>
        <input type="hidden" name="billing[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="billing:address_id" />
        <div class="row">
            <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress()->getFirstname() ? $this->getAddress() : $this->getQuote()->getCustomer())->setForceUseCustomerRequiredAttributes(!$this->isCustomerLoggedIn())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>

            <div class="field col-md-6">
                <label for="billing:company"><?php echo $this->__('Company') ?></label>
                <div class="input-box">
                    <input type="text" id="billing:company" name="billing[company]" value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text <?php echo $this->helper('onestepcheckout')->getAttributeValidationClass('company') ?>" />
                </div>
            </div>
    <?php if(!$this->isCustomerLoggedIn()): ?>
            <div class="field col-md-6">
                <label for="billing:email" class="required"><?php echo $this->__('Email Address') ?><span class="qs-required">*</span></label>
                <div class="input-box">
                    <input type="text" name="billing[email]" id="billing:email" value="<?php echo $this->escapeHtml($this->getAddress()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
                </div>
            </div>
    <?php endif; ?>
            <div class="field col-md-6">
                <label for="billing:country_id" class="required"><?php echo $this->__('Country') ?><span class="qs-required">*</span></label>
                <div class="input-box">
                    <?php echo $this->getCountryHtmlSelect('billing') ?>
                </div>
            </div>
            <div class="field col-md-6">
                <label for="billing:region_id" class="required"><?php echo $this->__('State / Province') ?><span class="qs-required">*</span></label>
                <div class="input-box">
                    <select id="billing:region_id" onchange="binllingProvince.reBuildDistrict(this.value);" name="billing[region_id]" title="<?php echo $this->__('State / Province') ?>" class="validate-select" style="display:none;">
                        <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                    </select>
                    <script type="text/javascript">
                        //<![CDATA[
                        $('billing:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                        //]]>
                    </script>
                    <input type="text" id="billing:region" name="billing[region]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"  title="<?php echo $this->__('State / Province') ?>" class="input-text <?php echo $this->helper('onestepcheckout')->getAttributeValidationClass('region') ?>" style="display:none;" />
                </div>
            </div>
            <div class="field col-md-6">
                <label for="billing:city" class="required"><?php echo $this->__('City') ?><span class="qs-required">*</span></label>
                <div class="input-box">
                    <input type="text" title="<?php echo $this->__('City') ?>" name="billing[city]" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>" class="input-text <?php echo $this->helper('onestepcheckout')->getAttributeValidationClass('city') ?>" id="billing:city" />
                </div>
            </div>
            <div class="field col-md-6">
                <label for="billing:postcode" class="required"><?php echo $this->__('Zip') ?><span class="qs-required">*</span></label>
                <div class="input-box">
                    <input type="text" title="<?php echo $this->__('Zip') ?>" name="billing[postcode]" id="billing:postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" class="input-text validate-zip-international <?php echo $this->helper('onestepcheckout')->getAttributeValidationClass('postcode') ?>" />
                </div>
            </div>
    <?php $_streetValidationClass = $this->helper('onestepcheckout')->getAttributeValidationClass('street'); ?>
            <div class="field col-md-6">
                <label for="billing:street1" class="required"><?php echo $this->__('Address') ?><span class="qs-required">*</span></label>
                <div class="input-box">
                    <input type="text" title="<?php echo $this->__('Street Address') ?>" name="billing[street][]" id="billing:street1" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                </div>
            </div>
    <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
    <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
            <div class="field col-md-6">
                <label for="billing:street<?php echo $_i ?>" class="required"><?php echo $this->__('Address ' . $_i) ?><span class="qs-required">*</span></label>
                <div class="input-box">
                    <input type="text" title="<?php echo $this->__('Street Address %s', $_i) ?>" name="billing[street][]" id="billing:street<?php echo $_i ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                </div>
            </div>
    <?php endfor; ?>
            <?php if ($this->helper('onestepcheckout')->isVatAttributeVisible()) : ?>
            <div class="field col-md-6">
                <label for="billing:vat_id"><?php echo $this->__('VAT Number') ?></label>
                <div class="input-box">
                    <input type="text" id="billing:vat_id" name="billing[vat_id]" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()) ?>" title="<?php echo $this->__('VAT Number') ?>" class="input-text <?php echo $this->helper('onestepcheckout')->getAttributeValidationClass('vat_id') ?>" />
                </div>
            </div>
            <?php endif; ?>
            <div class="address-additional-separator"></div>

            <div class="field col-md-6">
                <label for="billing:telephone" class="required"><?php echo $this->__('Telephone') ?><span class="qs-required">*</span></label>
                <div class="input-box">
                    <input type="text" name="billing[telephone]" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text <?php echo $this->helper('onestepcheckout')->getAttributeValidationClass('telephone') ?>" id="billing:telephone" />
                </div>
            </div>
            <div class="field col-md-6">
                <label for="billing:fax"><?php echo $this->__('Fax') ?></label>
                <div class="input-box">
                    <input type="text" name="billing[fax]" value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) ?>" title="<?php echo $this->__('Fax') ?>" class="input-text <?php echo $this->helper('onestepcheckout')->getAttributeValidationClass('fax') ?>" id="billing:fax" />
                </div>
            </div>

            <?php if(!$this->isCustomerLoggedIn()): ?>

                <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
                <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
                    <?php if ($_dob->isEnabled() || $_gender->isEnabled()): ?>
                        <?php if ($_dob->isEnabled()): ?>
                            <div class="field col-md-6">
                                <?php echo $_dob->setDate($this->getQuote()->getCustomerDob())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                            </div>
                        <?php endif; ?>
                        <?php if ($_gender->isEnabled()): ?>
                            <div class="field col-md-6">
                                <?php echo $_gender->setGender($this->getQuote()->getCustomerGender())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                            </div>
                        <?php endif ?>
                    <?php endif ?>

                <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
                <?php if ($_taxvat->isEnabled()): ?>
                        <div>
                            <?php echo $_taxvat->setTaxvat($this->getQuote()->getCustomerTaxvat())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                        </div>
                <?php endif ?>


            <?php endif; ?>
            <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
                <div class="control col-md-6">
                    <input type="checkbox" name="billing[save_in_address_book]" value="1" title="<?php echo $this->__('Save in address book') ?>" id="billing:save_in_address_book" onchange="if(window.shipping) shipping.setSameAsBilling(false);"<?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox" /><label for="billing:save_in_address_book"><?php echo $this->__('Save in address book') ?></label>
                </div>
            <?php else:?>
                <div class="no-display"><input type="hidden" name="billing[save_in_address_book]" value="1" /></div>
            <?php endif; ?>
            <?php echo $this->getChildHtml('form.additional.info'); ?>
        </div>
    </div>
    <?php /* Extensions placeholder */ ?>
    <?php echo $this->getChildHtml('checkout.onepage.billing.extra')?>

    <!-- fix browser autocomplete -->
	<div style="display:none !important">
		<input type="text" autocomplete="off" value="" />
		<input type="password" autocomplete="off" value=""/>
	</div>
	<!-- end fix browser autocomplete -->
    
    <?php if(!$this->isCustomerLoggedIn()): ?>
    
    	<?php
    	$guest_allowed = $this->getQuote()->isAllowedGuestCheckout();
    	if($guest_allowed): ?>
	    <div class="control">
	            <input type="checkbox" name="billing[create_account]" id="billing:create_account" value="1" title="<?php echo  $this->__('Create an account for later use') ?>"  class="checkbox" /><label for="billing:create_account"><?php echo  $this->__('Create an account for later use') ?></label>
	    </div>
	    <?php else:?>
	    	<input type="hidden" name="billing[create_account]" id="billing:create_account" value="1" />
	    <?php endif;?>
        
		<div class="row <?php if($guest_allowed):?>hidden<?php endif;?>" id="register-customer-password">
			<div class="field col-md-6">
				<label for="billing:customer_password" class="required"><?php echo $this->__('Password') ?><span class="qs-required">*</span></label>
				<div class="input-box">
					<input type="password" name="billing[customer_password]" title="<?php echo $this->__('Password') ?>" id="billing:customer_password" class="input-text validate-password <?php if(!$guest_allowed):?>required-entry<?php endif;?>" autocomplete="off" value=""/>
				</div>
			</div>
			<div class="field col-md-6">
				<label for="billing:confirm_password" class="required"><?php echo $this->__('Confirm Password') ?><span class="qs-required">*</span></label>
				<div class="input-box">
					<input type="password" name="billing[confirm_password]" title="<?php echo $this->__('Confirm Password') ?>" id="billing:confirm_password" class="input-text validate-cpassword <?php if(!$guest_allowed):?>required-entry<?php endif;?>" autocomplete="off" value=""/>
				</div>
			</div>
		</div>
    <?php endif;?>
    
    <?php if ($this->canShip()): ?>
        <div class="control <?php if (!Mage::helper('onestepcheckout')->isShowShippingForm()):?>hidden<?php endif;?>">
            <input type="checkbox" name="billing[use_for_shipping]" id="billing:use_for_shipping_yes" value="1"<?php if ($this->isUseBillingAddressForShipping()) {?> checked="checked"<?php }?> title="<?php echo  $this->__('Ship to this address') ?>" class="checkbox   " /><label for="billing:use_for_shipping_yes"><?php echo  $this->__('Ship to this address') ?></label>
        </div>
    <?php endif; ?>
    </div>
    <?php if (!$this->canShip()): ?>
        <input type="hidden" name="billing[use_for_shipping]" value="1" />
    <?php endif; ?>

</div>
<script type="text/javascript">
//<![CDATA[
    var billingRegionUpdater = new RegionUpdater('billing:country_id', 'billing:region', 'billing:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'billing:postcode');
//]]>
    var vnLocation = <?php echo Mage::helper('qsoft_custom')->getVnProvince()?>;
    var binllingProvince = new VnProvince(vnLocation, 'billing', 'billing:street2', 'billing:city','billing:country_id');

</script>
