<h3 class="qs-top-20"><?php echo $this->__('Shipping Address')?></h3>
<div class="form-list">
<?php if ($this->customerHasAddresses()): ?>
   <div class="field">
       <label for="shipping-address-select" class="notice"><?php echo $this->__('Select a shipping address from your address book or enter a new address.') ?></label>
       <div class="input-box">
           <?php echo $this->getAddressesHtmlSelect('shipping') ?>
       </div>
   </div>
<?php endif ?>
    <div id="shipping-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif ?>>
        <input type="hidden" name="shipping[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="shipping:address_id" />
        <div class="row">
            <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress())->setFieldIdFormat('shipping:%s')->setFieldNameFormat('shipping[%s]')->toHtml() ?>

            <div class="field col-md-6">
                <label for="shipping:company"><?php echo $this->__('Company') ?></label>
                <div class="input-box">
                    <input type="text" id="shipping:company" name="shipping[company]" value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text <?php echo $this->helper('onestepcheckout')->getAttributeValidationClass('company') ?>"/>
                </div>
            </div>
            <div class="field col-md-6">
                <label for="shipping:postcode" class="required"><?php echo $this->__('Zip') ?><span class="qs-required">*</span></label>
                <div class="input-box">
                    <input type="text" title="<?php echo $this->__('Zip') ?>" name="shipping[postcode]" id="shipping:postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" class="input-text validate-zip-international <?php echo $this->helper('onestepcheckout')->getAttributeValidationClass('postcode') ?>"  />
                </div>
            </div>
            <div class="field col-md-6">
                <label for="shipping:country_id" class="required"><?php echo $this->__('Country') ?><span class="qs-required">*</span></label>
                <div class="input-box">
                    <?php echo $this->getCountryHtmlSelect('shipping') ?>
                </div>
            </div>
            <div class="field col-md-6">
                <label for="shipping:region" class="required"><?php echo $this->__('State / Province') ?><span class="qs-required">*</span></label>
                <div class="input-box">
                    <select onchange="shippingProvince.reBuildDistrict(this.value);" id="shipping:region_id" name="shipping[region_id]" title="<?php echo $this->__('State / Province') ?>" class="validate-select" style="display:none;">
                        <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                    </select>
                    <script type="text/javascript">
                        //<![CDATA[
                        $('shipping:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                        //]]>
                    </script>
                    <input type="text" id="shipping:region" name="shipping[region]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>" title="<?php echo $this->__('State / Province') ?>" class="input-text <?php echo $this->helper('onestepcheckout')->getAttributeValidationClass('region') ?>" style="display:none;" />
                </div>
            </div>
            <div class="field col-md-6">
                <label for="shipping:city" class="required"><?php echo $this->__('City') ?><span class="qs-required">*</span></label>
                <div class="input-box">
                    <input type="text" title="<?php echo $this->__('City') ?>" name="shipping[city]" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>" class="input-text <?php echo $this->helper('onestepcheckout')->getAttributeValidationClass('city') ?>" id="shipping:city" />
                </div>
            </div>


    <?php $_streetValidationClass = $this->helper('onestepcheckout')->getAttributeValidationClass('street'); ?>
            <div class="field col-md-6">
                <label for="shipping:street1" class="required"><?php echo $this->__('Address') ?><span class="qs-required">*</span></label>
                <div class="input-box">
                    <input type="text" title="<?php echo $this->__('Street Address') ?>" name="shipping[street][]" id="shipping:street1" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                </div>
            </div>
    <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
    <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
            <div class="field col-md-6">
                <label for="shipping:street<?php echo $_i ?>" class="required"><?php echo $this->__('Address ' . $_i) ?><span class="qs-required">*</span></label>
                <div class="input-box">
                    <input type="text" title="<?php echo $this->__('Street Address %s', $_i) ?>" name="shipping[street][]" id="shipping:street<?php echo $_i ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                </div>
            </div>
    <?php endfor; ?>
            <?php if ($this->helper('onestepcheckout')->isVatAttributeVisible()) : ?>
            <div class="field col-md-6">
                <label for="billing:vat_id"><?php echo $this->__('VAT Number'); ?></label>
                <div class="input-box">
                    <input type="text" id="shipping:vat_id" name="shipping[vat_id]" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()); ?>" title="<?php echo $this->__('VAT Number'); ?>" class="input-text <?php echo $this->helper('onestepcheckout')->getAttributeValidationClass('vat_id') ?>" />
                </div>
            </div>
            <?php endif; ?>
            <div class="address-additional-separator"></div>

            <div class="field col-md-6">
                <label for="shipping:telephone" class="required"><?php echo $this->__('Telephone') ?><span class="qs-required">*</span></label>
                <div class="input-box">
                    <input type="text" name="shipping[telephone]" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text <?php echo $this->helper('onestepcheckout')->getAttributeValidationClass('telephone') ?>" id="shipping:telephone" />
                </div>
            </div>
            <div class="field col-md-6">
                <label for="shipping:fax"><?php echo $this->__('Fax') ?></label>
                <div class="input-box">
                    <input type="text" name="shipping[fax]" value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) ?>" title="<?php echo $this->__('Fax') ?>" class="input-text <?php echo $this->helper('onestepcheckout')->getAttributeValidationClass('fax') ?>" id="shipping:fax"  />
                </div>
            </div>

        <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
            <div class="control col-md-6">
                <input type="checkbox" name="shipping[save_in_address_book]" value="1" title="<?php echo $this->__('Save in address book') ?>" id="shipping:save_in_address_book" <?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox" /><label for="shipping:save_in_address_book"><?php echo $this->__('Save in address book') ?></label></div>
        <?php else:?>
            <div class="no-display"><input type="hidden" name="shipping[save_in_address_book]" value="1" /></div>
        <?php endif;?>
        </div>
    </div>
    <div class="control hidden">
        <input type="checkbox" name="shipping[same_as_billing]" id="shipping:same_as_billing" value="1"<?php if($this->getAddress()->getSameAsBilling()): ?> checked="checked"<?php endif; ?> title="<?php echo $this->__('Use Billing Address') ?>" class="checkbox" /><label for="shipping:same_as_billing"><?php echo $this->__('Use Billing Address') ?></label>
    </div>
</div>

<script type="text/javascript">
//<![CDATA[
    var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'shipping:postcode');
//]]>
var vnLocation = <?php echo Mage::helper('qsoft_custom')->getVnProvince()?>;
var shippingProvince = new VnProvince(vnLocation, 'shipping', 'shipping:street2', 'shipping:city','shipping:country_id');
</script>