<form action="<?php echo $this->getUrl('contacts/index/post') ?>" id="contactForm_inmobile_<?php echo $this->getItem()->getId(); ?>"  method="post">
    <div class="row ms-contact">
        <div class="col-sm-12 text-left">
            <span class="ms-title">Contact Form</span>
        </div>
        <div class="col-sm-4 text-left">
            <div class="form-group">
                <label for="name">Your name <em>*</em></label>
                <input class="form-control required-entry" type="text" name="name" id="name" value="" title="Your name" />
            </div>
            <div class="form-group">
                <label for="email">Your email <em>*</em></label>
                <input class="form-control required-entry validate-email" type="email" value="" name="email" id="email" title="Your email" />
            </div> 
            <div class="form-group">
                <label for="tel">Telephone</label>
                <input class="form-control" type="tel" value="" title="Telephone" name="telephone" id="telephone"/>
            </div>
        </div>
        <div class="col-sm-8 comment text-left">
            <div class="form-group">
                <label for="comment">Comment <em>*</em></label>
                <textarea  type="text"  class="form-control required-entry" name="comment" value="comment"></textarea>
            </div>
        </div>
        <br/>
        <div class="col-sm-12 text-left">  
            <button class="btn btn-primary" type="submit"><span>Submit</span></button>
        </div>
    </div>
</form>
<script>
    var contactForm_mobile_<?php echo $this->getItem()->getId() ?> = new VarienForm('contactForm_inmobile_<?php echo $this->getItem()->getId(); ?>', true);
</script>
