<div id="before-ajax-success">

</div>

<style>
    #before-ajax-success{
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: #fbfaf6;
        opacity: 0.5;
        z-index: 1000;
        display: none;
    }
</style>
<script type="text/javascript">
    function showLoadingMark() {
        jQuery('#before-ajax-success').show();
    }

    function hideLoadingMark() {
        jQuery('#before-ajax-success').hide();
    }

    jQuery(document).ready(function () {
        jQuery('.layerContainer li').click(function () {
            alert('fuck');
            jQuery(this).find('label').addClass('filter-checked');
        })
    })
</script>